// @generated
// This file is @generated by prost-build.
/// <p>Ends an ongoing call of the active SIP session of the active SIP account</p>
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SipEndCallRequest {
    /// Set to <code>True</code> to forcefully hang up the call
    #[prost(bool, tag="1")]
    pub hard_hangup: bool,
}
/// <p>Request to start the call with the active SIP session of the active SIP account</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SipStartCallRequest {
    /// SIP account name
    #[prost(string, tag="1")]
    pub callee_id: ::prost::alloc::string::String,
    /// Headers to include when starting the call
    #[prost(map="string, string", tag="2")]
    pub headers: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
/// <p>Request for registering a SIP account at a SIP server</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SipRegisterAccountRequest {
    /// Account name of the sip user. Usually something like <code>sip-user-1@mydomain.com</code> or <code>sip-user-1@192.168.123.123</code> which uses the default SIP port <code>5060</code>.
    /// Also a non-default SIP port can be specified via <code>sip-user-1@mydomain.com:5099</code> to connect to a SIP server running on port <code>5099</code>
    #[prost(string, tag="1")]
    pub account_name: ::prost::alloc::string::String,
    /// Password of the account
    #[prost(string, tag="2")]
    pub password: ::prost::alloc::string::String,
    /// Optional: authentication user name
    #[prost(string, tag="3")]
    pub auth_username: ::prost::alloc::string::String,
    /// Optional: outbound proxy address, e.g. <code>my.outbound.proxy.com</code>
    #[prost(string, tag="4")]
    pub outbound_proxy: ::prost::alloc::string::String,
}
/// <p>Request for starting a new SIP session for a specified account</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SipStartSessionRequest {
    /// Account name of the sip user. Usually something like <code>sip-user-1@mydomain.com</code> or <code>sip-user-1@192.168.123.123</code> which uses the default SIP port <code>5060</code>.
    /// Also a non-default SIP port can be specified via <code>sip-user-1@mydomain.com:5099</code> to connect to a SIP server running on port <code>5099</code>
    #[prost(string, tag="1")]
    pub account_name: ::prost::alloc::string::String,
    /// Auto-answer interval in seconds. The call will be automatically answered after this interval
    #[prost(int32, tag="2")]
    pub auto_answer_interval: i32,
}
/// <p>Request for transferring a call with or without headers</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SipTransferCallRequest {
    /// The account name or phone number to transfer the call to
    #[prost(string, tag="1")]
    pub transfer_id: ::prost::alloc::string::String,
    /// The headers to include when transferring the call
    #[prost(map="string, string", tag="2")]
    pub headers: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
/// <p>Status information for a SIP account, session, or call</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SipStatus {
    /// Account name of the sip user. Usually something like <code>sip-user-1@mydomain.com</code> or <code>sip-user-1@192.168.123.123</code> which uses the default SIP port <code>5060</code>.
    /// Also a non-default SIP port can be specified via <code>sip-user-1@mydomain.com:5099</code> to connect to a SIP server running on port <code>5099</code>
    #[prost(string, tag="1")]
    pub account_name: ::prost::alloc::string::String,
    /// Timestamp of the status
    #[prost(message, optional, tag="2")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    /// Status type
    #[prost(enumeration="sip_status::StatusType", tag="3")]
    pub status_type: i32,
    /// SIP account name
    #[prost(string, tag="4")]
    pub callee_id: ::prost::alloc::string::String,
    /// SIP account of the transfer
    #[prost(string, tag="5")]
    pub transfer_call_id: ::prost::alloc::string::String,
    /// Headers to include when calling outbound or transfer
    #[prost(map="string, string", tag="6")]
    pub headers: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    /// More detailed description of the status
    #[prost(string, tag="7")]
    pub description: ::prost::alloc::string::String,
    /// Name of the exception
    #[prost(string, tag="8")]
    pub exception_name: ::prost::alloc::string::String,
    /// Traceback of the exception
    #[prost(string, tag="9")]
    pub exception_traceback: ::prost::alloc::string::String,
    /// session name of the NLU session
    #[prost(string, tag="10")]
    pub nlu_session_name: ::prost::alloc::string::String,
}
/// Nested message and enum types in `SipStatus`.
pub mod sip_status {
    /// Types of status
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum StatusType {
        /// No session is currently active
        NoSession = 0,
        /// SIP account is registered at a SIP server
        Registered = 1,
        /// SIP account is ready to call
        Ready = 2,
        /// SIP account is being called, i.e. inbound/incoming call
        IncomingCallInitiated = 3,
        /// SIP account starts calling, i.e. outbound/outgoing call
        OutgoingCallInitiated = 4,
        /// SIP account outbound call is connected
        OutgoingCallConnected = 5,
        /// SIP account incoming call is connected
        IncomingCallConnected = 6,
        /// SIP account starts transferring the call
        TransferCallInitiated = 7,
        /// SIP account hangs up the ongoing call
        SoftHangupInitiated = 8,
        /// SIP account forcefully hangs up by terminating the SIP program
        HardHangupInitiated = 9,
        /// SIP account cannot accept the incoming call
        IncomingCallFailed = 10,
        /// SIP account cannot do an outbound call
        OutgoingCallFailed = 11,
        /// SIP account finished the ongoing incoming call
        IncomingCallFinished = 12,
        /// SIP account finished the ongoing outgoing call
        OutgoingCallFinished = 13,
        /// Registration of SIP account to SIP server failed
        SessionRegistrationFailed = 14,
        /// SIP account started a new SIP session via a SIP server
        SessionStarted = 15,
        /// SIP account ended active sip session with SIP server
        SessionEnded = 16,
        /// SIP account cannot transfer the call
        TransferCallFailed = 17,
        /// Microphone is muted
        MicrophoneMuted = 18,
        /// Microphone is unmuted
        MicrophoneUnmuted = 19,
        /// Microphone has played wav files
        MicrophoneWavFilesPlayed = 20,
        /// No ongoing call
        NoOngoingCall = 21,
    }
    impl StatusType {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::NoSession => "NO_SESSION",
                Self::Registered => "REGISTERED",
                Self::Ready => "READY",
                Self::IncomingCallInitiated => "INCOMING_CALL_INITIATED",
                Self::OutgoingCallInitiated => "OUTGOING_CALL_INITIATED",
                Self::OutgoingCallConnected => "OUTGOING_CALL_CONNECTED",
                Self::IncomingCallConnected => "INCOMING_CALL_CONNECTED",
                Self::TransferCallInitiated => "TRANSFER_CALL_INITIATED",
                Self::SoftHangupInitiated => "SOFT_HANGUP_INITIATED",
                Self::HardHangupInitiated => "HARD_HANGUP_INITIATED",
                Self::IncomingCallFailed => "INCOMING_CALL_FAILED",
                Self::OutgoingCallFailed => "OUTGOING_CALL_FAILED",
                Self::IncomingCallFinished => "INCOMING_CALL_FINISHED",
                Self::OutgoingCallFinished => "OUTGOING_CALL_FINISHED",
                Self::SessionRegistrationFailed => "SESSION_REGISTRATION_FAILED",
                Self::SessionStarted => "SESSION_STARTED",
                Self::SessionEnded => "SESSION_ENDED",
                Self::TransferCallFailed => "TRANSFER_CALL_FAILED",
                Self::MicrophoneMuted => "MICROPHONE_MUTED",
                Self::MicrophoneUnmuted => "MICROPHONE_UNMUTED",
                Self::MicrophoneWavFilesPlayed => "MICROPHONE_WAV_FILES_PLAYED",
                Self::NoOngoingCall => "NO_ONGOING_CALL",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "NO_SESSION" => Some(Self::NoSession),
                "REGISTERED" => Some(Self::Registered),
                "READY" => Some(Self::Ready),
                "INCOMING_CALL_INITIATED" => Some(Self::IncomingCallInitiated),
                "OUTGOING_CALL_INITIATED" => Some(Self::OutgoingCallInitiated),
                "OUTGOING_CALL_CONNECTED" => Some(Self::OutgoingCallConnected),
                "INCOMING_CALL_CONNECTED" => Some(Self::IncomingCallConnected),
                "TRANSFER_CALL_INITIATED" => Some(Self::TransferCallInitiated),
                "SOFT_HANGUP_INITIATED" => Some(Self::SoftHangupInitiated),
                "HARD_HANGUP_INITIATED" => Some(Self::HardHangupInitiated),
                "INCOMING_CALL_FAILED" => Some(Self::IncomingCallFailed),
                "OUTGOING_CALL_FAILED" => Some(Self::OutgoingCallFailed),
                "INCOMING_CALL_FINISHED" => Some(Self::IncomingCallFinished),
                "OUTGOING_CALL_FINISHED" => Some(Self::OutgoingCallFinished),
                "SESSION_REGISTRATION_FAILED" => Some(Self::SessionRegistrationFailed),
                "SESSION_STARTED" => Some(Self::SessionStarted),
                "SESSION_ENDED" => Some(Self::SessionEnded),
                "TRANSFER_CALL_FAILED" => Some(Self::TransferCallFailed),
                "MICROPHONE_MUTED" => Some(Self::MicrophoneMuted),
                "MICROPHONE_UNMUTED" => Some(Self::MicrophoneUnmuted),
                "MICROPHONE_WAV_FILES_PLAYED" => Some(Self::MicrophoneWavFilesPlayed),
                "NO_ONGOING_CALL" => Some(Self::NoOngoingCall),
                _ => None,
            }
        }
    }
}
/// <p>History of SIP status</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SipStatusHistoryResponse {
    /// History of SIP status
    #[prost(message, repeated, tag="1")]
    pub status_history: ::prost::alloc::vec::Vec<SipStatus>,
}
/// <p>Plays a list of wav files</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SipPlayWavFilesRequest {
    /// Wav files as bytes in a list that will be played
    #[prost(bytes="vec", repeated, tag="1")]
    pub wav_files: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
include!("ondewo.sip.tonic.rs");
// @@protoc_insertion_point(module)
