// @generated
// This file is @generated by prost-build.
/// <p>Represents a Synthesize Request.</p>
/// <p>A Synthesize Request contains the information need to perform a text to speech conversion.</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SynthesizeRequest {
    /// Required. Represents the text that will be transformed to speech.
    ///
    /// <p>The text may be plain text, or it may embed SSML markup, phonemes and voice-control tags to
    /// shape how it is spoken. The sections below list every supported form with a copy-paste example.
    /// Which forms take effect depends on the pipeline (model) selected via
    /// <code>RequestConfig.t2s_pipeline_id</code>; unsupported tags are stripped and the plain text is
    /// still spoken.</p>
    ///
    /// <p><b>1. Plain text</b></p>
    /// <ul>
    ///    <li>Simple text: <pre><code>Hello, how are you?</code></pre></li>
    /// </ul>
    ///
    /// <p><b>2. SSML <code>&lt;say-as&gt;</code> tags (local vits / qwen3-tts and cloud providers)</b></p>
    /// <p>Rewrites the enclosed text into its spoken form (spelled out letters, digits, symbols, ...).
    /// Supported by the local normalization pipeline and forwarded to the cloud providers.</p>
    /// <ul>
    ///    <li>Phone: <pre><code>&lt;say-as interpret-as=&quot;phone&quot;&gt;+12354321&lt;/say-as&gt;</code></pre></li>
    ///    <li>Email: <pre><code>&lt;say-as interpret-as=&quot;email&quot;&gt;voices@ondewo.com&lt;/say-as&gt;</code></pre></li>
    ///    <li>URL: <pre><code>&lt;say-as interpret-as=&quot;url&quot;&gt;ondewo.com/en/&lt;/say-as&gt;</code></pre></li>
    ///    <li>Spell (spell out each character): <pre><code>&lt;say-as interpret-as=&quot;spell&quot;&gt;AP732&lt;/say-as&gt;</code></pre></li>
    ///    <li>Spell with names (e.g. &quot;A like Anton&quot;): <pre><code>&lt;say-as interpret-as=&quot;spell-with-names&quot;&gt;AHO32&lt;/say-as&gt;</code></pre></li>
    ///    <li>Callsigns short: <pre><code>&lt;say-as interpret-as=&quot;callsign-short&quot;&gt;AUA439&lt;/say-as&gt;</code></pre></li>
    ///    <li>Callsigns long: <pre><code>&lt;say-as interpret-as=&quot;callsign-long&quot;&gt;AAL439&lt;/say-as&gt;</code></pre></li>
    /// </ul>
    ///
    /// <p><b>3. Pauses / breaks</b></p>
    /// <ul>
    ///    <li>Break tag (seconds): <pre><code>I am going to take a 2 seconds break &lt;break time=&quot;2.0&quot;/&gt; done</code></pre></li>
    ///    <li>Break tag (milliseconds, cloud providers): <pre><code>please wait &lt;break time=&quot;500ms&quot;/&gt; done</code></pre></li>
    /// </ul>
    ///
    /// <p><b>4. Phonemes / pronunciation control</b></p>
    /// <p>The phoneme alphabet depends exclusively on the model type:</p>
    /// <p><b>4a. IPA phonemes (vits and cloud providers only)</b> - the vits models and the cloud
    /// providers (Amazon Polly, Microsoft Azure and Google Cloud TTS) control pronunciation with the SSML
    /// <code>&lt;phoneme&gt;</code> element using the IPA alphabet (<code>alphabet=&quot;ipa&quot;</code>).
    /// The IPA string goes in the <code>ph</code> attribute and the written word between the tags:</p>
    /// <ul>
    ///    <li>English: <pre><code>I would like a &lt;phoneme alphabet=&quot;ipa&quot; ph=&quot;t&#601;&#712;me&#618;to&#650;&quot;&gt;tomato&lt;/phoneme&gt; please</code></pre></li>
    ///    <li>German: <pre><code>Ich h&auml;tte gerne ein &lt;phoneme alphabet=&quot;ipa&quot; ph=&quot;&#712;ba&#618;&#643;pi&#720;l&quot;&gt;Beispiel&lt;/phoneme&gt; bitte</code></pre></li>
    /// </ul>
    /// <p><b>4b. Arpabet phonemes (glow model only)</b> - the glow model controls pronunciation with
    /// Arpabet phonemes, supplied through the same SSML <code>&lt;phoneme&gt;</code> element but with
    /// <code>alphabet=&quot;arpabet&quot;</code>. The ARPAbet transcription goes in the <code>ph</code>
    /// attribute and the written word between the tags (the phonemes are <b>not</b> written in curly
    /// braces <code>{}</code> in the request text):</p>
    /// <ul>
    ///    <li>English: <pre><code>Please say &lt;phoneme alphabet=&quot;arpabet&quot; ph=&quot;T EH1 S T&quot;&gt;test&lt;/phoneme&gt; out loud</code></pre></li>
    ///    <li>German: <pre><code>Ich sage &lt;phoneme alphabet=&quot;arpabet&quot; ph=&quot;T EH1 S T&quot;&gt;test&lt;/phoneme&gt; laut</code></pre></li>
    /// </ul>
    /// <p><b>4c. qwen3-tts has no phonemes - use the verbalized form instead</b> - the qwen3-tts models
    /// do <b>not</b> support Arpabet or IPA phonemes; the <code>&lt;phoneme&gt;</code> element and its
    /// <code>ph</code> string are ignored. Instead, to have a special text (symbols, codes,
    /// abbreviations, ...) spoken correctly, pass its <b>verbalization</b>: the plain, written-out spoken
    /// form of the text in the target language. For example, to have <code>A-7+8*</code> pronounced
    /// correctly:</p>
    /// <ul>
    ///    <li>English: <pre><code>ai dash seven plus eight asterisk</code></pre></li>
    ///    <li>German: <pre><code>ah bindestrich sieben plus acht sternchen</code></pre></li>
    /// </ul>
    ///
    /// <p><b>5. Voice control for qwen3-tts (emotion / style / prosody)</b></p>
    /// <p>These ONDEWO-namespaced tags are compiled into the model instruction and stripped from the
    /// spoken text, so the transcription stays the plain sentence while the delivery changes. They only
    /// take effect on the qwen3-tts <b>CustomVoice</b> model; on the base and voicedesign models they are
    /// stripped and a warning is logged.</p>
    /// <ul>
    ///    <li>Style - one of the five primary styles <code>apologetic</code>, <code>calm</code>,
    ///      <code>empathetic</code>, <code>firm</code>, <code>lively</code>, or one of the accepted
    ///      synonyms <code>cheerful</code> / <code>happy</code> / <code>joyful</code>,
    ///      <code>sad</code> / <code>sorrowful</code>, <code>angry</code> / <code>furious</code>,
    ///      <code>excited</code>, <code>serious</code>, <code>tender</code> / <code>gentle</code>.
    ///      An unknown name falls back to <code>neutral</code> and a warning is logged:
    ///      <pre><code>&lt;ondewo:style name=&quot;calm&quot;&gt;please stay calm everything will be fine&lt;/ondewo:style&gt;</code></pre></li>
    ///    <li>Emphasis - selects the intensity tier of the chosen style: <code>strong</code> (intense),
    ///      <code>moderate</code> (the default when no emphasis is given) or <code>reduced</code> /
    ///      <code>none</code> (mild):
    ///      <pre><code>&lt;ondewo:style name=&quot;firm&quot;&gt;&lt;emphasis level=&quot;strong&quot;&gt;listen carefully&lt;/emphasis&gt;&lt;/ondewo:style&gt;</code></pre></li>
    ///    <li>Prosody - <code>rate</code> (<code>x-slow</code>/<code>slow</code>/<code>medium</code>/<code>fast</code>/<code>x-fast</code>
    ///      or a percentage such as <code>+20%</code>/<code>-20%</code>/<code>120%</code>),
    ///      <code>pitch</code> (<code>x-low</code>/<code>low</code>/<code>medium</code>/<code>high</code>/<code>x-high</code>,
    ///      a semitone offset such as <code>+4st</code>/<code>-4st</code> or a percentage such as
    ///      <code>+10%</code>/<code>-10%</code>) and
    ///      <code>volume</code> (<code>silent</code>/<code>x-soft</code>/<code>soft</code>/<code>medium</code>/<code>loud</code>/<code>x-loud</code>
    ///      or a decibel offset such as <code>+6dB</code>/<code>-6dB</code>):
    ///      <pre><code>&lt;prosody rate=&quot;slow&quot; pitch=&quot;+4st&quot; volume=&quot;loud&quot;&gt;hello there&lt;/prosody&gt;</code></pre></li>
    ///    <li>Nested combination (style + emphasis + prosody):
    ///      <pre><code>&lt;ondewo:style name=&quot;calm&quot;&gt;&lt;emphasis level=&quot;moderate&quot;&gt;&lt;prosody rate=&quot;slow&quot; pitch=&quot;low&quot; volume=&quot;soft&quot;&gt;hello there&lt;/prosody&gt;&lt;/emphasis&gt;&lt;/ondewo:style&gt;</code></pre></li>
    ///    <li>Free-form instruction (CustomVoice only) - describe the delivery in natural language in the
    ///      <code>instruction</code> attribute. The attribute value is used verbatim as the model
    ///      instruction and takes precedence over the style / emphasis / prosody tags; the wrapped inner
    ///      text is kept as the spoken text and it should be always in English:
    ///      <pre><code>&lt;ondewo:instruct instruction=&quot;speak slowly in a warm and reassuring tone&quot;&gt;hello there&lt;/ondewo:instruct&gt;</code></pre></li>
    ///    <li>Inline audio tags (CustomVoice only) - emotional expressions / sound effects in square
    ///      brackets. They are compiled into the instruction and stripped from the spoken text. The
    ///      supported tags are:
    ///      <ul>
    ///        <li>Voice-related: <code>\[laughs\]</code>, <code>\[laughs harder\]</code>,
    ///          <code>\[starts laughing\]</code>, <code>\[wheezing\]</code>, <code>\[whispers\]</code>,
    ///          <code>\[sighs\]</code>, <code>\[exhales\]</code>, <code>\[sarcastic\]</code>,
    ///          <code>\[curious\]</code>, <code>\[excited\]</code>, <code>\[crying\]</code>,
    ///          <code>\[snorts\]</code>, <code>\[mischievously\]</code></li>
    ///        <li>Sound effects: <code>\[gunshot\]</code>, <code>\[applause\]</code>,
    ///          <code>\[clapping\]</code>, <code>\[explosion\]</code>, <code>\[swallows\]</code>,
    ///          <code>\[gulps\]</code></li>
    ///        <li>Unique and special: <code>\[sings\]</code>, <code>\[woo\]</code>, <code>\[fart\]</code></li>
    ///        <li>Accent (variable form): <code>\[strong &lt;accent&gt; accent\]</code>, e.g.
    ///          <code>\[strong French accent\]</code></li>
    ///      </ul>
    ///      <pre><code>\[whispers\] hello there</code></pre></li>
    /// </ul>
    /// <p>See also <code>RequestConfig.instruction</code> for supplying the instruction / voice
    /// description directly instead of embedding it in the text.</p>
    ///
    /// <p><b>6. Provider-specific SSML (cloud pipelines only)</b></p>
    /// <p>Each cloud provider documents its own SSML vocabulary; use the elements matching the provider
    /// behind the selected pipeline. Standard <code>&lt;prosody&gt;</code>, <code>&lt;emphasis&gt;</code>
    /// and <code>&lt;break&gt;</code> are common to all three.</p>
    /// <ul>
    ///    <li>Google Cloud TTS: <pre><code>&lt;google:style name=&quot;calm&quot;&gt;please stay calm everything will be fine&lt;/google:style&gt;</code></pre></li>
    ///    <li>Microsoft Azure: <pre><code>&lt;mstts:express-as style=&quot;cheerful&quot;&gt;please stay calm everything will be fine&lt;/mstts:express-as&gt;</code></pre></li>
    ///    <li>Amazon Polly (whispered): <pre><code>&lt;amazon:effect name=&quot;whispered&quot;&gt;please stay calm everything will be fine&lt;/amazon:effect&gt;</code></pre></li>
    ///    <li>Amazon Polly (soft phonation): <pre><code>&lt;amazon:effect phonation=&quot;soft&quot;&gt;please stay calm everything will be fine&lt;/amazon:effect&gt;</code></pre></li>
    /// </ul>
    #[prost(string, tag="1")]
    pub text: ::prost::alloc::string::String,
    /// Required. Represents the specifications needed to do the text to speech transformation.
    #[prost(message, optional, tag="2")]
    pub config: ::core::option::Option<RequestConfig>,
}
/// <p>BatchSynthesizeRequest message is used to send a batch request for synthesis.</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchSynthesizeRequest {
    /// Repeated field holding individual synthesis requests that make up the batch request.
    #[prost(message, repeated, tag="1")]
    pub batch_request: ::prost::alloc::vec::Vec<SynthesizeRequest>,
}
/// <p>StreamingSynthesizeRequest is used to perform streaming synthesize.</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StreamingSynthesizeRequest {
    /// Required. Represents the text that will be transformed to speech.
    /// All the properties according to the input text in SynthesizeRequest can be also applied here.
    #[prost(string, tag="1")]
    pub text: ::prost::alloc::string::String,
    /// Required. Represents the specifications needed to do the text to speech transformation.
    #[prost(message, optional, tag="2")]
    pub config: ::core::option::Option<RequestConfig>,
}
/// <p>BatchSynthesizeResponse message is used to store the responses for a batch synthesis request.</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchSynthesizeResponse {
    /// Repeated field holding individual synthesis responses that correspond to the input requests in the batch.
    #[prost(message, repeated, tag="1")]
    pub batch_response: ::prost::alloc::vec::Vec<SynthesizeResponse>,
}
/// <p>Represents a Configuration for the text to speech conversion.</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RequestConfig {
    /// Required. Represents the pipeline id of the model configuration that will be used.
    #[prost(string, tag="1")]
    pub t2s_pipeline_id: ::prost::alloc::string::String,
    /// Optional. t2s_service_config provides the configuration of the service such as API key, bearer tokens, JWT,
    /// and other header information as key value pairs, e.g., <pre><code>MY_API_KEY=&apos;LKJDIFe244LKJOI&apos;</code></pre>
    ///
    /// A. For Amazon T2S service, the following arguments should be passed:
    /// <ul>
    ///    <li>A1. <code>aws_access_key_id</code> (required) Access key id to access Amazon WEB Service.</li>
    ///    <li>A2. <code>aws_secret_access_key</code> (required) Secret access key to access Amazon WEB Service.</li>
    ///    <li>A3. <code>region</code> (required) Region name of Amazon Server.</li>
    /// </ul>
    /// Example:
    /// <pre><code>t2s_config_service={&apos;aws_access_key_id&apos;: &apos;YOUR_AWS_ACCESS_KEY_ID&apos;, &apos;aws_secret_access_key&apos;: &apos;YOUR_AWS_SECRET_ACCESS_KEY&apos;, &apos;region&apos;: &apos;YOUR_AMAZON_SERVER_REGION_NAME&apos;}</code></pre>
    ///
    /// B. For ElevenLabs T2s service, the following arguments should be passed:
    /// <ul>
    ///    <li>B1. <code>api_key</code> (required) API key of ElevenLabs cloud provider to access its T2S service.</li>
    /// </ul>
    /// Example:
    /// <pre><code>t2s_config_service={&apos;api_key&apos;: &apos;YOUR_ELEVENLABS_API_KEY&apos;}</code></pre>
    ///
    /// C. For Google cloud T2S service, the following arguments should be passed:
    /// <ul>
    ///    <li>C1. <code>api_key</code> (required) API key of Google cloud provider to access its T2S service.</li>
    ///    <li>C2. <code>api_endpoint</code> (optional) Regional API endpoint of Google cloud T2S service.
    ///      (Defaults to &apos;eu-texttospeech.googleapis.com&apos;)</li>
    /// </ul>
    /// Example:
    /// <pre><code>t2s_config_service={&apos;api_key&apos;: &apos;YOUR_GOOGLE_CLOUD_API_KEY&apos;, &apos;api_endpoint&apos;: &apos;YOUR_GOOGLE_CLOUD_API_ENDPOINT&apos;}</code></pre>
    ///
    /// D. For Microsoft Azure T2s service, the following arguments should be passed:
    /// <ul>
    ///    <li>D1. <code>subscription_key</code> (required) Subscription key to access Microsoft Azure Service.</li>
    ///    <li>D2. <code>region</code> (required) Region name of Microsoft Azure Server.</li>
    /// </ul>
    /// Example:
    /// <pre><code>t2s_config_service={&apos;subscription_key&apos;: &apos;YOUR_MICROSOFT_AZURE_SUBSCRIPTION_KEY&apos;, &apos;region&apos;: &apos;YOUR_MICROSOFT_AZURE_SERVER_REGION_NAME&apos;}</code></pre>
    ///
    /// Note: ondewo-t2s will raise an error if you don&apos;t pass any of the required arguments above.
    #[prost(message, optional, tag="9")]
    pub t2s_service_config: ::core::option::Option<::prost_types::Struct>,
    /// Optional. Defines the cloud provider's specific configuration for using text to speech cloud services
    /// The default value is None.
    #[prost(message, optional, tag="10")]
    pub t2s_cloud_provider_config: ::core::option::Option<T2sCloudProviderConfig>,
    /// Optional. Define a dict which specifies the phonemes for a special word.
    #[prost(message, optional, tag="12")]
    pub word_to_phoneme_mapping: ::core::option::Option<::prost_types::Struct>,
    /// Optional. Define an instruction or prompt to be passed to the TTS/LLM backend for this request.
    ///
    /// <p>This field is only honored by the <b>qwen3-tts-voicedesign</b> model, where it is a
    /// natural-language description of the target voice to design, e.g.
    /// <pre><code>a calm female voice with a slight British accent</code></pre></p>
    /// <p>It is ignored by every other pipeline, including the qwen3-tts CustomVoice and base models and
    /// the local vits / glow-tts models. To control the delivery / emotion of the qwen3-tts CustomVoice
    /// model, embed the control tags in the request text instead (see <code>SynthesizeRequest.text</code>),
    /// not via this field.</p>
    #[prost(string, optional, tag="13")]
    pub instruction: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(oneof="request_config::OneofLengthScale", tags="2")]
    pub oneof_length_scale: ::core::option::Option<request_config::OneofLengthScale>,
    #[prost(oneof="request_config::OneofNoiseScale", tags="3")]
    pub oneof_noise_scale: ::core::option::Option<request_config::OneofNoiseScale>,
    #[prost(oneof="request_config::OneofSampleRate", tags="4")]
    pub oneof_sample_rate: ::core::option::Option<request_config::OneofSampleRate>,
    #[prost(oneof="request_config::OneofPcm", tags="5")]
    pub oneof_pcm: ::core::option::Option<request_config::OneofPcm>,
    #[prost(oneof="request_config::OneofAudioFormat", tags="6")]
    pub oneof_audio_format: ::core::option::Option<request_config::OneofAudioFormat>,
    #[prost(oneof="request_config::OneofUseCache", tags="7")]
    pub oneof_use_cache: ::core::option::Option<request_config::OneofUseCache>,
    #[prost(oneof="request_config::OneofT2sNormalization", tags="11")]
    pub oneof_t2s_normalization: ::core::option::Option<request_config::OneofT2sNormalization>,
}
/// Nested message and enum types in `RequestConfig`.
pub mod request_config {
    #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
    pub enum OneofLengthScale {
        /// Optional. This parameter is used for time stretching which is the process of
        /// changing the speed or duration of an audio.
        /// It should be much more than 1.0. 0 is not a valid number for this variable.
        /// The default value is 1.
        #[prost(float, tag="2")]
        LengthScale(f32),
    }
    #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
    pub enum OneofNoiseScale {
        /// Optional. Defines the noise in the generated audio.
        /// It should be between 0.0 and 1.
        /// The default value is 0.0
        #[prost(float, tag="3")]
        NoiseScale(f32),
    }
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum OneofSampleRate {
        /// Optional. Defines the sample rate of the generated wav file.
        /// The default value is 22050.
        #[prost(int32, tag="4")]
        SampleRate(i32),
    }
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum OneofPcm {
        /// Optional. Defines the pulse-code modulation of the wav file.
        /// The default value is PCM_16.
        #[prost(enumeration="super::Pcm", tag="5")]
        Pcm(i32),
    }
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum OneofAudioFormat {
        /// Optional. Defines the format of the desired audio.
        /// The default value is wav.
        #[prost(enumeration="super::AudioFormat", tag="6")]
        AudioFormat(i32),
    }
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum OneofUseCache {
        /// Optional. Define if cache should be used or not.
        /// The default value is False.
        #[prost(bool, tag="7")]
        UseCache(bool),
    }
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum OneofT2sNormalization {
        /// Optional. Define t2s_normalization config parameters for this specific request.
        /// The default values are set in the config file and the values set via RequestConfig are set just for
        /// this specific request and will not update the pipeline.
        #[prost(message, tag="11")]
        T2sNormalization(super::T2sNormalization),
    }
}
/// <p>Configuration for cloud provider settings for Text-to-Speech (T2S).</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct T2sCloudProviderConfig {
    /// Configuration for Eleven Labs text-to-speech provider.
    #[prost(message, optional, tag="1")]
    pub t2s_cloud_provider_config_elevenlabs: ::core::option::Option<T2sCloudProviderConfigElevenLabs>,
    /// Configuration for Google text-to-speech provider.
    #[prost(message, optional, tag="2")]
    pub t2s_cloud_provider_config_google: ::core::option::Option<T2sCloudProviderConfigGoogle>,
    /// Configuration for Microsoft text-to-speech provider.
    #[prost(message, optional, tag="3")]
    pub t2s_cloud_provider_config_microsoft: ::core::option::Option<T2sCloudProviderConfigMicrosoft>,
}
/// <p>Configuration details specific to the Eleven Labs text-to-speech provider.</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct T2sCloudProviderConfigElevenLabs {
    /// Stability level for inference, influencing consistency of generated speech. It is in the range \[0.0, 1.0\].
    #[prost(float, tag="1")]
    pub stability: f32,
    /// Boost value for similarity to enhance the similarity of the generated voice to a target voice.
    /// It is in the range \[0.0, 1.0\].
    #[prost(float, tag="2")]
    pub similarity_boost: f32,
    /// Style parameter to control the expression or emotion in speech. It is in the range \[0.0, 1.0\].
    #[prost(float, tag="3")]
    pub style: f32,
    /// Enables or disables speaker boost for emphasis on clarity and loudness.
    #[prost(bool, tag="4")]
    pub use_speaker_boost: bool,
    /// Specifies type of text normalization to apply during processing. Available options are 'auto', 'on', and 'off'.
    #[prost(string, tag="5")]
    pub apply_text_normalization: ::prost::alloc::string::String,
}
/// <p>Configuration details specific to the Microsoft text-to-speech provider.</p>
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct T2sCloudProviderConfigMicrosoft {
    /// Determines whether to use the default speaker voice.
    #[prost(bool, tag="1")]
    pub use_default_speaker: bool,
}
/// <p>Configuration details specific to the Google text-to-speech provider.</p>
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct T2sCloudProviderConfigGoogle {
    /// Speaking rate for inference, controlling the speed of generated speech. It is in the range \[0.25, 4.0\].
    #[prost(float, tag="1")]
    pub speaking_rate: f32,
    /// Volume gain in dB applied to the generated speech. It is in the range \[-96.0, 16.0\].
    #[prost(float, tag="2")]
    pub volume_gain_db: f32,
    /// Pitch adjustment for inference, allowing control over voice pitch. It is in the range in the range \[-20.0, 20.0\].
    #[prost(float, tag="3")]
    pub pitch: f32,
}
/// <p>Represents a Synthesize Response.</p>
/// <p>A Synthesize Response contains the generated audio, requested text and all other properties of this generated audio.</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SynthesizeResponse {
    /// Required. The unique identifier (UUID) assigned to the generated audio.
    #[prost(string, tag="1")]
    pub audio_uuid: ::prost::alloc::string::String,
    /// Required. Generated file with the parameters described in request.
    #[prost(bytes="vec", tag="2")]
    pub audio: ::prost::alloc::vec::Vec<u8>,
    /// Required. Time taken to generate the audio, in seconds.
    #[prost(float, tag="3")]
    pub generation_time: f32,
    /// Required. Length (duration) of the generated audio, in seconds.
    #[prost(float, tag="4")]
    pub audio_length: f32,
    /// Required. Text from which audio was generated.
    #[prost(string, tag="5")]
    pub text: ::prost::alloc::string::String,
    /// Required. Configuration from which audio was generated.
    #[prost(message, optional, tag="6")]
    pub config: ::core::option::Option<RequestConfig>,
    /// Optional. Normalized text.
    #[prost(string, tag="7")]
    pub normalized_text: ::prost::alloc::string::String,
    /// Optional. Sampling rate of the generated audio, in Hertz (Hz).
    #[prost(float, tag="8")]
    pub sample_rate: f32,
}
/// <p>Represents a Streaming Synthesize Response.</p>
/// <p>A Streaming Synthesize Response contains the generated audio, requested text and and
/// all other properties of this generated audio.</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StreamingSynthesizeResponse {
    /// Required. The unique identifier (UUID) assigned to the generated audio.
    #[prost(string, tag="1")]
    pub audio_uuid: ::prost::alloc::string::String,
    /// Required. Generated file with the parameters described in request.
    #[prost(bytes="vec", tag="2")]
    pub audio: ::prost::alloc::vec::Vec<u8>,
    /// Required. Time taken to generate the audio, in seconds.
    #[prost(float, tag="3")]
    pub generation_time: f32,
    /// Required. Length (duration) of the generated audio, in seconds.
    #[prost(float, tag="4")]
    pub audio_length: f32,
    /// Required. Text from which audio was generated.
    #[prost(string, tag="5")]
    pub text: ::prost::alloc::string::String,
    /// Required. Configuration from which audio was generated.
    #[prost(message, optional, tag="6")]
    pub config: ::core::option::Option<RequestConfig>,
    /// Optional. Normalized text.
    #[prost(string, tag="7")]
    pub normalized_text: ::prost::alloc::string::String,
    /// Optional. Sampling rate of the generated audio, in Hertz (Hz).
    #[prost(float, tag="8")]
    pub sample_rate: f32,
}
// /////////////
// NORMALIZE //
// /////////////

/// <p>NormalizeTextRequest message is used to request text normalization.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NormalizeTextRequest {
    /// The ID of the text-to-speech pipeline.
    #[prost(string, tag="1")]
    pub t2s_pipeline_id: ::prost::alloc::string::String,
    /// The text to be normalized.
    #[prost(string, tag="2")]
    pub text: ::prost::alloc::string::String,
}
/// <p>NormalizeTextResponse message is used to store the normalized text response.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NormalizeTextResponse {
    /// The normalized text.
    #[prost(string, tag="1")]
    pub normalized_text: ::prost::alloc::string::String,
}
// ////////////////////
// GET SERVICE INFO //
// ////////////////////

/// <p>Version information of the service</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct T2sGetServiceInfoResponse {
    /// version number
    #[prost(string, tag="1")]
    pub version: ::prost::alloc::string::String,
}
// //////////////////////
// LIST T2S PIPELINES //
// //////////////////////

/// <p>Pipeline Request representation.</p>
/// <p>The request message for ListT2sPipelines.</p>
/// <p>Filter pipelines by attributed in request.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListT2sPipelinesRequest {
    /// Optional. Define the language/ languages.
    #[prost(string, repeated, tag="1")]
    pub languages: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Optional. Define the speaker sex.
    #[prost(string, repeated, tag="2")]
    pub speaker_sexes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Optional. Define the pipeline owner/ owners.
    #[prost(string, repeated, tag="3")]
    pub pipeline_owners: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Optional. Define the speaker name/ names.
    #[prost(string, repeated, tag="4")]
    pub speaker_names: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Optional. Define the domain/ domains.
    #[prost(string, repeated, tag="5")]
    pub domains: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// <p>Pipeline Response representation.</p>
/// <p>The response message for ListT2sPipelines.</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListT2sPipelinesResponse {
    /// Required. Representation of a list of pipelines configurations.
    /// Retrieved by ListT2sPipelines, containing the configurations of
    /// pipelines with the specifications received in the ListT2sPipelinesRequest.
    #[prost(message, repeated, tag="1")]
    pub pipelines: ::prost::alloc::vec::Vec<Text2SpeechConfig>,
}
// //////////////////////
// LIST T2S LANGUAGES //
// //////////////////////

/// <p>Language Request representation.</p>
/// <p>The request message for ListT2sLanguages.</p>
/// <p>Filter languages of pipelines by attributed in request.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListT2sLanguagesRequest {
    /// Optional. Define the speaker sex.
    #[prost(string, repeated, tag="1")]
    pub speaker_sexes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Optional. Define the pipeline owner/ owners.
    #[prost(string, repeated, tag="2")]
    pub pipeline_owners: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Optional. Define the speaker name/ names.
    #[prost(string, repeated, tag="3")]
    pub speaker_names: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Optional. Define the domain/ domains.
    #[prost(string, repeated, tag="4")]
    pub domains: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// <p>Language Response representation.</p>
/// <p>The response message for ListT2sLanguages.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListT2sLanguagesResponse {
    /// Required. Define the language/ languages that satisfy/ies
    /// the specifications in the ListT2sLanguagesRequest.
    #[prost(string, repeated, tag="1")]
    pub languages: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
// ////////////////////
// LIST T2S DOMAINS //
// ////////////////////

/// <p>Domain Request representation.</p>
/// <p>The request message for ListT2sDomains.</p>
/// <p>Filter domains of pipelines by attributed in request.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListT2sDomainsRequest {
    /// Optional. Define the speaker sex.
    #[prost(string, repeated, tag="1")]
    pub speaker_sexes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Optional. Define the pipeline owner/ owners.
    #[prost(string, repeated, tag="2")]
    pub pipeline_owners: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Optional. Define the speaker name/ names.
    #[prost(string, repeated, tag="3")]
    pub speaker_names: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Optional. Define the language/ languages.
    #[prost(string, repeated, tag="4")]
    pub languages: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// <p>Domains Response representation.</p>
/// <p>The response message for ListT2sDomains.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListT2sDomainsResponse {
    /// Required. Define the domain/ domains that satisfy/ies
    /// the specifications in the ListT2sDomainsRequest.
    #[prost(string, repeated, tag="1")]
    pub domains: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
// //////////////////////
// LIST T2S NORMALIZATION PIPELINES //
// //////////////////////

/// <p>The request message for ListT2sNormalizationPipelines.</p>
/// <p>Filter pipelines by attributed in request.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListT2sNormalizationPipelinesRequest {
    /// Optional. Define the language.
    #[prost(string, tag="1")]
    pub language: ::prost::alloc::string::String,
}
/// <p>Pipeline Response representation.</p>
/// <p>The response message for ListT2sNormalizationPipelines.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListT2sNormalizationPipelinesResponse {
    /// Required. Representation of a list of normalization pipelines configurations.
    /// Retrieved by ListT2sNormalizationPipelines, containing the configurations of
    /// normalization pipelines with the specifications received in the ListT2sNormalizationPipelinesRequest.
    #[prost(string, repeated, tag="1")]
    pub t2s_normalization_pipelines: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
// ///////////////////////
// UPDATE T2S PIPELINE //
// ///////////////////////

/// <p>Pipeline Id representation.</p>
/// <p>Used in the creation, deletion and getter of pipelines.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct T2sPipelineId {
    /// Required. Defines the id of the pipeline.
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
// /////////////////////////
// Text-to-Speech Config //
// /////////////////////////

/// <p>Configuration of text-to-speech models representation.</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Text2SpeechConfig {
    /// Required. Defines the id of the pipeline.
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    /// Required. Defines the description of the pipeline representation.
    #[prost(message, optional, tag="2")]
    pub description: ::core::option::Option<T2sDescription>,
    /// Required. Defines if the pipeline is active or inactive.
    #[prost(bool, tag="3")]
    pub active: bool,
    /// Required. Defines the inference of the pipeline representation.
    #[prost(message, optional, tag="4")]
    pub inference: ::core::option::Option<T2sInference>,
    /// Required. Defines the normalization process of the pipeline representation.
    #[prost(message, optional, tag="5")]
    pub normalization: ::core::option::Option<T2sNormalization>,
    /// Required. Defines the postprocessing process of the pipeline representation.
    #[prost(message, optional, tag="6")]
    pub postprocessing: ::core::option::Option<Postprocessing>,
}
/// <p>T2SDescription message is used to describe the text-to-speech service.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct T2sDescription {
    /// The language supported by the service.
    #[prost(string, tag="1")]
    pub language: ::prost::alloc::string::String,
    /// The speaker's sex or gender.
    #[prost(string, tag="2")]
    pub speaker_sex: ::prost::alloc::string::String,
    /// The owner of the text-to-speech pipeline.
    #[prost(string, tag="3")]
    pub pipeline_owner: ::prost::alloc::string::String,
    /// Additional comments or notes.
    #[prost(string, tag="4")]
    pub comments: ::prost::alloc::string::String,
    /// The name of the speaker.
    #[prost(string, tag="5")]
    pub speaker_name: ::prost::alloc::string::String,
    /// The domain or context of the service.
    #[prost(string, tag="6")]
    pub domain: ::prost::alloc::string::String,
}
/// <p>T2SInference message is used to specify the text-to-speech inference settings.</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct T2sInference {
    /// The type of inference, selecting which of the settings below is applied:
    /// composite_inference (two-stage text-to-mel then mel-to-audio) or
    /// single_inference (single-stage text-to-audio).
    #[prost(string, tag="1")]
    pub r#type: ::prost::alloc::string::String,
    /// Composite (two-stage) inference settings, used when type selects composite inference.
    #[prost(message, optional, tag="2")]
    pub composite_inference: ::core::option::Option<CompositeInference>,
    /// Single (one-stage) inference settings, used when type selects single inference.
    #[prost(message, optional, tag="3")]
    pub single_inference: ::core::option::Option<SingleInference>,
    /// Caching settings.
    #[prost(message, optional, tag="4")]
    pub caching: ::core::option::Option<Caching>,
}
/// <p>CompositeInference message combines text-to-mel and mel-to-audio inference settings.</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CompositeInference {
    /// Text-to-mel inference settings.
    #[prost(message, optional, tag="1")]
    pub text2mel: ::core::option::Option<Text2Mel>,
    /// Mel-to-audio inference settings.
    #[prost(message, optional, tag="2")]
    pub mel2audio: ::core::option::Option<Mel2Audio>,
}
/// <p>SingleInference message inference settings of text2audio models.</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SingleInference {
    /// Text-to-audio inference settings.
    #[prost(message, optional, tag="1")]
    pub text2audio: ::core::option::Option<Text2Audio>,
}
/// <p>Text2Mel message contains settings for text-to-mel inference.</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Text2Mel {
    /// The type of text-to-mel inference, selecting which of the settings below is applied
    /// (glow_tts or glow_tts_triton).
    #[prost(string, tag="1")]
    pub r#type: ::prost::alloc::string::String,
    /// GlowTTS inference settings.
    #[prost(message, optional, tag="2")]
    pub glow_tts: ::core::option::Option<GlowTts>,
    /// GlowTTS Triton inference settings.
    #[prost(message, optional, tag="3")]
    pub glow_tts_triton: ::core::option::Option<GlowTtsTriton>,
}
/// <p>Text2Audio message contains settings for text-to-audio inference.</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Text2Audio {
    /// The type of text-to-audio inference, selecting which of the settings below is applied:
    /// a local model (vits, vits_triton) or a cloud / neural service (t2s_cloud_service_elevenlabs,
    /// t2s_cloud_service_amazon, t2s_cloud_service_google, t2s_cloud_service_microsoft,
    /// qwen3_tts_custom_voice, qwen3_tts_base).
    #[prost(string, tag="1")]
    pub r#type: ::prost::alloc::string::String,
    /// Vits inference settings.
    #[prost(message, optional, tag="2")]
    pub vits: ::core::option::Option<Vits>,
    /// Vits Triton inference settings.
    #[prost(message, optional, tag="3")]
    pub vits_triton: ::core::option::Option<VitsTriton>,
    /// ElevenLabs cloud service inference settings.
    #[prost(message, optional, tag="4")]
    pub t2s_cloud_service_elevenlabs: ::core::option::Option<T2sCloudServiceElevenLabs>,
    /// Amazon cloud service inference settings.
    #[prost(message, optional, tag="5")]
    pub t2s_cloud_service_amazon: ::core::option::Option<T2sCloudServiceAmazon>,
    /// Google cloud service inference settings.
    #[prost(message, optional, tag="6")]
    pub t2s_cloud_service_google: ::core::option::Option<T2sCloudServiceGoogle>,
    /// Microsoft cloud service inference settings.
    #[prost(message, optional, tag="7")]
    pub t2s_cloud_service_microsoft: ::core::option::Option<T2sCloudServiceMicrosoft>,
    /// Qwen3-TTS-custom-voice inference settings.
    #[prost(message, optional, tag="8")]
    pub qwen3_tts_custom_voice: ::core::option::Option<Qwen3TtsCustomVoice>,
    /// Qwen3-TTS-base inference settings for voice cloning.
    #[prost(message, optional, tag="9")]
    pub qwen3_tts_base: ::core::option::Option<Qwen3TtsBase>,
}
/// <p>GlowTTS message contains settings for the GlowTTS inference.</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GlowTts {
    /// The batch size for inference.
    #[prost(int64, tag="1")]
    pub batch_size: i64,
    /// Flag indicating whether to use GPU for inference.
    #[prost(bool, tag="2")]
    pub use_gpu: bool,
    /// The length scale for inference.
    #[prost(float, tag="3")]
    pub length_scale: f32,
    /// The noise scale for inference.
    #[prost(float, tag="4")]
    pub noise_scale: f32,
    /// The path to the GlowTTS model.
    #[prost(string, tag="5")]
    pub path: ::prost::alloc::string::String,
    /// Repeated field containing the cleaners for text normalization.
    #[prost(string, repeated, tag="6")]
    pub cleaners: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// The path to the parameter configuration.
    #[prost(string, tag="7")]
    pub param_config_path: ::prost::alloc::string::String,
}
/// <p>GlowTTSTriton message contains settings for the GlowTTS Triton inference.</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GlowTtsTriton {
    /// The batch size for inference.
    #[prost(int64, tag="1")]
    pub batch_size: i64,
    /// The length scale for inference.
    #[prost(float, tag="2")]
    pub length_scale: f32,
    /// The noise scale for inference.
    #[prost(float, tag="3")]
    pub noise_scale: f32,
    /// Repeated field containing the cleaners for text normalization.
    #[prost(string, repeated, tag="4")]
    pub cleaners: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// The maximum text length allowed.
    #[prost(int64, tag="5")]
    pub max_text_length: i64,
    /// The path to the parameter configuration.
    #[prost(string, tag="6")]
    pub param_config_path: ::prost::alloc::string::String,
    /// The name of the Triton model.
    #[prost(string, tag="7")]
    pub triton_model_name: ::prost::alloc::string::String,
    /// The host of the Triton inference server which serves the model.
    #[prost(string, tag="8")]
    pub triton_server_host: ::prost::alloc::string::String,
    /// The port of the Triton inference server which serves the model.
    #[prost(int64, tag="9")]
    pub triton_server_port: i64,
}
/// <p>Vits message contains settings for the Vits inference.</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Vits {
    /// The batch size for inference.
    #[prost(int64, tag="1")]
    pub batch_size: i64,
    /// Flag indicating whether to use GPU for inference.
    #[prost(bool, tag="2")]
    pub use_gpu: bool,
    /// The length scale for inference.
    #[prost(float, tag="3")]
    pub length_scale: f32,
    /// The noise scale for inference.
    #[prost(float, tag="4")]
    pub noise_scale: f32,
    /// The path to the Vits model.
    #[prost(string, tag="5")]
    pub path: ::prost::alloc::string::String,
    /// Repeated field containing the cleaners for text normalization.
    #[prost(string, repeated, tag="6")]
    pub cleaners: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// The path to the parameter configuration.
    #[prost(string, tag="7")]
    pub param_config_path: ::prost::alloc::string::String,
}
/// <p>VitsTriton message contains settings for the Vits Triton inference.</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VitsTriton {
    /// The batch size for inference.
    #[prost(int64, tag="1")]
    pub batch_size: i64,
    /// The length scale for inference.
    #[prost(float, tag="2")]
    pub length_scale: f32,
    /// The noise scale for inference.
    #[prost(float, tag="3")]
    pub noise_scale: f32,
    /// Repeated field containing the cleaners for text normalization.
    #[prost(string, repeated, tag="4")]
    pub cleaners: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// The maximum text length allowed.
    #[prost(int64, tag="5")]
    pub max_text_length: i64,
    /// The path to the parameter configuration.
    #[prost(string, tag="6")]
    pub param_config_path: ::prost::alloc::string::String,
    /// The name of the Triton model.
    #[prost(string, tag="7")]
    pub triton_model_name: ::prost::alloc::string::String,
    /// The host of the Triton inference server which serves the model.
    #[prost(string, tag="8")]
    pub triton_server_host: ::prost::alloc::string::String,
    /// The port of the Triton inference server which serves the model.
    #[prost(int64, tag="9")]
    pub triton_server_port: i64,
}
/// <p>T2sCloudServiceElevenLabs message contains settings for the ElevenLabs Cloud service inference.</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct T2sCloudServiceElevenLabs {
    /// Language of the generated audio. It should be 4-Letter language code.
    #[prost(string, tag="1")]
    pub language_code: ::prost::alloc::string::String,
    /// Model ID indicating the name of the model
    #[prost(string, tag="2")]
    pub model_id: ::prost::alloc::string::String,
    /// Voice ID indicating the speaker
    #[prost(string, tag="3")]
    pub voice_id: ::prost::alloc::string::String,
    /// Voice setting of the inference
    #[prost(message, optional, tag="4")]
    pub voice_settings: ::core::option::Option<VoiceSettings>,
    /// Flag to indicate applying text normalization
    #[prost(string, tag="5")]
    pub apply_text_normalization: ::prost::alloc::string::String,
}
/// <p>VoiceSettings message contains settings for ElevenLabs inference.</p>
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct VoiceSettings {
    /// stability value for elevenlabs inference
    #[prost(float, tag="1")]
    pub stability: f32,
    /// similarity boost value for ElevenLabs inference.
    #[prost(float, tag="2")]
    pub similarity_boost: f32,
    /// style boost value for ElevenLabs inference.
    #[prost(float, tag="3")]
    pub style: f32,
    /// Flag to indicate speaker boost
    #[prost(bool, tag="4")]
    pub use_speaker_boost: bool,
}
/// <p>T2sCloudServiceAmazon message contains settings for the Amazon Cloud service inference.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct T2sCloudServiceAmazon {
    /// Voice ID indicating the speaker
    #[prost(string, tag="1")]
    pub voice_id: ::prost::alloc::string::String,
    /// Model id for the inference server.
    #[prost(string, tag="2")]
    pub model_id: ::prost::alloc::string::String,
}
/// <p>T2sCloudServiceGoogle message contains settings for the Google Cloud service inference.</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct T2sCloudServiceGoogle {
    /// Voice ID indicating the speaker
    #[prost(string, tag="1")]
    pub voice_id: ::prost::alloc::string::String,
    /// Speaking rate to control the speed of audio.
    #[prost(float, tag="2")]
    pub speaking_rate: f32,
    /// Volume gain in db to control volume of the audio.
    #[prost(float, tag="3")]
    pub volume_gain_db: f32,
    /// pitch value of the audio
    #[prost(float, tag="4")]
    pub pitch: f32,
    /// speaker_language indicating the speaker language code
    #[prost(string, tag="5")]
    pub speaker_language: ::prost::alloc::string::String,
}
/// <p>T2sCloudServiceMicrosoft message contains settings for the Microsoft Cloud service inference.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct T2sCloudServiceMicrosoft {
    /// Voice ID indicating the speaker.
    #[prost(string, tag="1")]
    pub voice_id: ::prost::alloc::string::String,
    /// Flag to indicate using the default speaker.
    #[prost(bool, tag="2")]
    pub use_default_speaker: bool,
}
/// <p>Qwen3TtsCustomVoice message contains settings for inference of qwen3-TTS-CustomVoice model.</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Qwen3TtsCustomVoice {
    /// Voice id indicating the speaker name
    #[prost(string, tag="1")]
    pub voice_id: ::prost::alloc::string::String,
    /// Model name for the inference server.
    #[prost(string, tag="2")]
    pub model_name: ::prost::alloc::string::String,
    /// Language for inference server
    #[prost(string, tag="3")]
    pub language: ::prost::alloc::string::String,
    /// Host name for the inference server
    #[prost(string, tag="4")]
    pub qwen3_tts_server_host: ::prost::alloc::string::String,
    /// Port of the inference server
    #[prost(int64, tag="5")]
    pub qwen3_tts_server_port: i64,
    /// Authorization headers for the inference server
    #[prost(message, optional, tag="6")]
    pub qwen3_tts_server_header: ::core::option::Option<::prost_types::Struct>,
}
/// <p>Qwen3TtsBase message contains settings for inference of qwen3-TTS-Base model.</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Qwen3TtsBase {
    /// Model name for the inference server.
    #[prost(string, tag="1")]
    pub model_name: ::prost::alloc::string::String,
    /// Language for inference server
    #[prost(string, tag="2")]
    pub language: ::prost::alloc::string::String,
    /// Path of the embedding file
    #[prost(string, tag="3")]
    pub embedding_path: ::prost::alloc::string::String,
    /// Host name for the inference server
    #[prost(string, tag="4")]
    pub qwen3_tts_server_host: ::prost::alloc::string::String,
    /// Port of the inference server
    #[prost(int64, tag="5")]
    pub qwen3_tts_server_port: i64,
    /// Authorization headers for the inference server
    #[prost(message, optional, tag="6")]
    pub qwen3_tts_server_header: ::core::option::Option<::prost_types::Struct>,
}
/// <p>Mel2Audio message contains settings for mel-to-audio inference.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Mel2Audio {
    /// The type of mel-to-audio inference (vocoder), selecting which of the settings below is applied
    /// (mb_melgan_triton, hifi_gan or hifi_gan_triton).
    #[prost(string, tag="1")]
    pub r#type: ::prost::alloc::string::String,
    /// MbMelgan Triton inference settings.
    #[prost(message, optional, tag="2")]
    pub mb_melgan_triton: ::core::option::Option<MbMelganTriton>,
    /// HiFiGan inference settings.
    #[prost(message, optional, tag="3")]
    pub hifi_gan: ::core::option::Option<HiFiGan>,
    /// HiFiGan Triton inference settings.
    #[prost(message, optional, tag="4")]
    pub hifi_gan_triton: ::core::option::Option<HiFiGanTriton>,
}
/// <p>HiFiGan message contains settings for the HiFiGan inference.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HiFiGan {
    /// Flag indicating whether to use GPU for inference.
    #[prost(bool, tag="1")]
    pub use_gpu: bool,
    /// The batch size for inference.
    #[prost(int64, tag="2")]
    pub batch_size: i64,
    /// The path to the HiFiGan configuration.
    #[prost(string, tag="3")]
    pub config_path: ::prost::alloc::string::String,
    /// The path to the HiFiGan model.
    #[prost(string, tag="4")]
    pub model_path: ::prost::alloc::string::String,
}
/// <p>HiFiGanTriton message contains settings for the HiFiGan Triton inference.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HiFiGanTriton {
    /// The path to the HiFiGan Triton configuration.
    #[prost(string, tag="1")]
    pub config_path: ::prost::alloc::string::String,
    /// The name of the Triton model.
    #[prost(string, tag="2")]
    pub triton_model_name: ::prost::alloc::string::String,
    /// The host of the Triton inference server which serves the model.
    #[prost(string, tag="3")]
    pub triton_server_host: ::prost::alloc::string::String,
    /// The port of the Triton inference server which serves the model.
    #[prost(int64, tag="4")]
    pub triton_server_port: i64,
}
/// <p>MbMelganTriton message contains settings for the MbMelgan Triton inference.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MbMelganTriton {
    /// The path to the MbMelgan Triton configuration.
    #[prost(string, tag="1")]
    pub config_path: ::prost::alloc::string::String,
    /// The path to the MbMelgan statistics.
    #[prost(string, tag="2")]
    pub stats_path: ::prost::alloc::string::String,
    /// The name of the Triton model.
    #[prost(string, tag="3")]
    pub triton_model_name: ::prost::alloc::string::String,
    /// The host of the Triton inference server which serves the model.
    #[prost(string, tag="4")]
    pub triton_server_host: ::prost::alloc::string::String,
    /// The port of the Triton inference server which serves the model.
    #[prost(int64, tag="5")]
    pub triton_server_port: i64,
}
/// <p>Caching message contains settings for caching.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Caching {
    /// Flag indicating whether caching is active.
    #[prost(bool, tag="1")]
    pub active: bool,
    /// The maximum size of the memory cache.
    #[prost(int64, tag="2")]
    pub memory_cache_max_size: i64,
    /// The sampling rate for caching.
    #[prost(int64, tag="3")]
    pub sampling_rate: i64,
    /// Flag indicating whether to load cache.
    #[prost(bool, tag="4")]
    pub load_cache: bool,
    /// Flag indicating whether to save cache.
    #[prost(bool, tag="5")]
    pub save_cache: bool,
    /// The directory path to save the cache.
    #[prost(string, tag="6")]
    pub cache_save_dir: ::prost::alloc::string::String,
}
/// <p>Represents the configuration for text-to-speech normalization.</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct T2sNormalization {
    /// The language for which the normalization is applied.
    #[prost(string, tag="1")]
    pub language: ::prost::alloc::string::String,
    /// The pipeline(s) used for normalization.
    #[prost(string, repeated, tag="2")]
    pub pipeline: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// The ID of the custom phonemizer, if used.
    #[prost(string, tag="3")]
    pub custom_phonemizer_id: ::prost::alloc::string::String,
    /// Custom length scales for different text types.
    #[prost(message, optional, tag="4")]
    pub custom_length_scales: ::core::option::Option<T2sCustomLengthScales>,
    /// The mapping for Arpabet phonemes.
    #[prost(string, tag="5")]
    pub arpabet_mapping: ::prost::alloc::string::String,
    /// The mapping for numeric expressions.
    #[prost(string, tag="6")]
    pub numeric_mapping: ::prost::alloc::string::String,
    /// The mapping for callsigns.
    #[prost(string, tag="7")]
    pub callsigns_mapping: ::prost::alloc::string::String,
    /// The mapping for phoneme correction.
    #[prost(string, tag="8")]
    pub phoneme_correction_mapping: ::prost::alloc::string::String,
}
/// <p>Postprocessing message contains settings for postprocessing.</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Postprocessing {
    /// The duration of silence in seconds.
    #[prost(float, tag="1")]
    pub silence_secs: f32,
    /// Repeated field containing pipeline names.
    #[prost(string, repeated, tag="2")]
    pub pipeline: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Logmnse postprocessing settings.
    #[prost(message, optional, tag="3")]
    pub logmmse: ::core::option::Option<Logmnse>,
    /// Wiener postprocessing settings.
    #[prost(message, optional, tag="4")]
    pub wiener: ::core::option::Option<Wiener>,
    /// Apodization postprocessing settings.
    #[prost(message, optional, tag="5")]
    pub apodization: ::core::option::Option<Apodization>,
}
/// <p>Logmnse message contains settings for Logmnse postprocessing.</p>
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Logmnse {
    /// The initial noise value.
    #[prost(int64, tag="1")]
    pub initial_noise: i64,
    /// The window size.
    #[prost(int64, tag="2")]
    pub window_size: i64,
    /// The noise threshold.
    #[prost(float, tag="3")]
    pub noise_threshold: f32,
}
/// <p>Wiener message contains settings for Wiener postprocessing.</p>
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Wiener {
    /// The frame length.
    #[prost(int64, tag="1")]
    pub frame_len: i64,
    /// The LPC order.
    #[prost(int64, tag="2")]
    pub lpc_order: i64,
    /// The number of iterations.
    #[prost(int64, tag="3")]
    pub iterations: i64,
    /// The alpha value.
    #[prost(float, tag="4")]
    pub alpha: f32,
    /// The threshold value.
    #[prost(float, tag="5")]
    pub thresh: f32,
}
/// <p>Apodization message contains settings for apodization postprocessing.</p>
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Apodization {
    /// The duration of apodization in seconds.
    #[prost(float, tag="1")]
    pub apodization_secs: f32,
}
/// <p>T2SCustomLengthScales message contains custom length scales for text types.</p>
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct T2sCustomLengthScales {
    /// The custom length scale for general text.
    #[prost(float, tag="1")]
    pub text: f32,
    /// The custom length scale for email text.
    #[prost(float, tag="2")]
    pub email: f32,
    /// The custom length scale for URL text.
    #[prost(float, tag="3")]
    pub url: f32,
    /// The custom length scale for phone number text.
    #[prost(float, tag="4")]
    pub phone: f32,
    /// The custom length scale for spelled-out text.
    #[prost(float, tag="5")]
    pub spell: f32,
    /// The custom length scale for spelled-out text with names.
    #[prost(float, tag="6")]
    pub spell_with_names: f32,
    /// The custom length scale for long callsigns.
    #[prost(float, tag="7")]
    pub callsign_long: f32,
    /// The custom length scale for short callsigns.
    #[prost(float, tag="8")]
    pub callsign_short: f32,
}
/// <p>PhonemizerId message represents the ID of a phonemizer.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PhonemizerId {
    /// The ID of the phonemizer.
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
/// <p>CustomPhonemizerProto message represents a custom phonemizer.</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CustomPhonemizerProto {
    /// The ID of the custom phonemizer.
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    /// Repeated field of Map messages representing word-to-phoneme mappings.
    #[prost(message, repeated, tag="2")]
    pub maps: ::prost::alloc::vec::Vec<Map>,
}
/// <p>Map message represents a word-to-phoneme mapping in a custom phonemizer.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Map {
    /// The word to be mapped.
    #[prost(string, tag="1")]
    pub word: ::prost::alloc::string::String,
    /// The phoneme groups associated with the word.
    #[prost(string, tag="2")]
    pub phoneme_groups: ::prost::alloc::string::String,
}
/// <p>ListCustomPhonemizerResponse message represents the response for listing custom phonemizers.</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListCustomPhonemizerResponse {
    /// Repeated field of CustomPhonemizerProto messages representing the custom phonemizers.
    #[prost(message, repeated, tag="1")]
    pub phonemizers: ::prost::alloc::vec::Vec<CustomPhonemizerProto>,
}
/// <p>ListCustomPhonemizerRequest message represents the request for listing custom phonemizers.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListCustomPhonemizerRequest {
    /// Repeated field of pipeline IDs to filter the list of custom phonemizers.
    #[prost(string, repeated, tag="1")]
    pub pipeline_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// <p>UpdateCustomPhonemizerRequest message represents the request for updating a custom phonemizer.</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateCustomPhonemizerRequest {
    /// The ID of the custom phonemizer to be updated.
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    /// The update method.
    #[prost(enumeration="update_custom_phonemizer_request::UpdateMethod", tag="2")]
    pub update_method: i32,
    /// Repeated field of Map messages representing word-to-phoneme mappings.
    #[prost(message, repeated, tag="3")]
    pub maps: ::prost::alloc::vec::Vec<Map>,
}
/// Nested message and enum types in `UpdateCustomPhonemizerRequest`.
pub mod update_custom_phonemizer_request {
    /// The update method to be used.
    /// UpdateMethod enum defines the method for updating custom phonemizers.
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum UpdateMethod {
        /// Add new words, replacing existing ones.
        ExtendHard = 0,
        /// Add new words if they are not already present.
        ExtendSoft = 1,
        /// Replace all words in the phonemizer with new ones.
        Replace = 2,
    }
    impl UpdateMethod {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::ExtendHard => "extend_hard",
                Self::ExtendSoft => "extend_soft",
                Self::Replace => "replace",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "extend_hard" => Some(Self::ExtendHard),
                "extend_soft" => Some(Self::ExtendSoft),
                "replace" => Some(Self::Replace),
                _ => None,
            }
        }
    }
}
/// <p>CreateCustomPhonemizerRequest message represents the request for creating a custom phonemizer.</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateCustomPhonemizerRequest {
    /// The prefix for the custom phonemizer ID.
    #[prost(string, tag="1")]
    pub prefix: ::prost::alloc::string::String,
    /// Repeated field of Map messages representing word-to-phoneme mappings.
    #[prost(message, repeated, tag="2")]
    pub maps: ::prost::alloc::vec::Vec<Map>,
}
// /////////////////
// VOICE CLONING //
// /////////////////

/// <p>VoiceCloningRequest message represents the request for cloning a voice.</p>
/// <p>A VoiceCloningRequest contains a sample audio of the speaker to be cloned together with
/// its transcription and the information about the speaker and the model to use for cloning.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VoiceCloningRequest {
    /// Required. The sample audio of the speaker whose voice should be cloned.
    #[prost(bytes="vec", tag="1")]
    pub sample_audio: ::prost::alloc::vec::Vec<u8>,
    /// Required. The transcription of the sample audio.
    #[prost(string, tag="2")]
    pub transcription: ::prost::alloc::string::String,
    /// Required. The name of the speaker to associate with the cloned voice.
    #[prost(string, tag="3")]
    pub speaker_name: ::prost::alloc::string::String,
    /// Required. The language of the speaker in the sample audio.
    #[prost(string, tag="4")]
    pub speaker_language: ::prost::alloc::string::String,
    /// Required. The name of the model used for voice cloning.
    #[prost(string, tag="5")]
    pub model_name: ::prost::alloc::string::String,
}
/// <p>Represents a pulse-code modulation technique.</p>
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Pcm {
    /// 16-bit pulse-code modulation.
    Pcm16 = 0,
    /// 24-bit pulse-code modulation.
    Pcm24 = 1,
    /// 32-bit pulse-code modulation.
    Pcm32 = 2,
    /// Signed 8-bit pulse-code modulation.
    S8 = 3,
    /// Unsigned 8-bit pulse-code modulation.
    U8 = 4,
    /// Floating-point (32-bit) pulse-code modulation.
    Float = 5,
    /// Floating-point (64-bit) pulse-code modulation.
    Double = 6,
}
impl Pcm {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Pcm16 => "PCM_16",
            Self::Pcm24 => "PCM_24",
            Self::Pcm32 => "PCM_32",
            Self::S8 => "PCM_S8",
            Self::U8 => "PCM_U8",
            Self::Float => "FLOAT",
            Self::Double => "DOUBLE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PCM_16" => Some(Self::Pcm16),
            "PCM_24" => Some(Self::Pcm24),
            "PCM_32" => Some(Self::Pcm32),
            "PCM_S8" => Some(Self::S8),
            "PCM_U8" => Some(Self::U8),
            "FLOAT" => Some(Self::Float),
            "DOUBLE" => Some(Self::Double),
            _ => None,
        }
    }
}
/// <p>AudioFormat enum represents various audio file formats for storing digital audio data.</p>
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum AudioFormat {
    /// Waveform Audio File Format (WAV)
    Wav = 0,
    /// Free Lossless Audio Codec (FLAC)
    Flac = 1,
    /// Core Audio Format (CAF)
    Caf = 2,
    /// MPEG Audio Layer III (MP3)
    Mp3 = 3,
    /// Advanced Audio Coding (AAC)
    Aac = 4,
    /// Ogg Vorbis (OGG)
    Ogg = 5,
    /// Windows Media Audio (WMA)
    Wma = 6,
}
impl AudioFormat {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Wav => "wav",
            Self::Flac => "flac",
            Self::Caf => "caf",
            Self::Mp3 => "mp3",
            Self::Aac => "aac",
            Self::Ogg => "ogg",
            Self::Wma => "wma",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "wav" => Some(Self::Wav),
            "flac" => Some(Self::Flac),
            "caf" => Some(Self::Caf),
            "mp3" => Some(Self::Mp3),
            "aac" => Some(Self::Aac),
            "ogg" => Some(Self::Ogg),
            "wma" => Some(Self::Wma),
            _ => None,
        }
    }
}
include!("ondewo.t2s.tonic.rs");
// @@protoc_insertion_point(module)
