// @generated
// This file is @generated by prost-build.
/// The request message
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetAnswerRequest {
    /// Required. The name of the session this query is sent to. Format:
    /// <code>projects/&lt;Project ID&gt;/agent/sessions/&lt;Session ID&gt;</code>.
    /// It&apos;s up to the API caller to choose an appropriate session ID. It can be a random number or
    /// some type of user identifier (preferably hashed). The length of the session
    /// ID must not exceed 36 bytes.
    #[prost(string, tag="1")]
    pub session_id: ::prost::alloc::string::String,
    /// Required. The context of the request. A message containing a string (in the form of a sentence) and a
    /// language code.
    #[prost(message, optional, tag="2")]
    pub text: ::core::option::Option<super::nlu::TextInput>,
    /// Maximal number of answers returned
    #[prost(int32, tag="3")]
    pub max_num_answers: i32,
    /// Threshold (minimal score) to give back reader result
    #[prost(float, tag="4")]
    pub threshold_reader: f32,
    /// Threshold (minimal score) to give back retriever result
    #[prost(float, tag="5")]
    pub threshold_retriever: f32,
    /// Threshold (minimal score) overall probability
    #[prost(float, tag="6")]
    pub threshold_overall: f32,
    /// Reader model name
    #[prost(string, tag="7")]
    pub reader_model_name: ::prost::alloc::string::String,
    /// Optional. Filters applied to the urls, to restrict the retrieved documents.
    #[prost(message, optional, tag="8")]
    pub url_filter: ::core::option::Option<UrlFilter>,
}
/// Message containing the response for retrieving answers.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetAnswerResponse {
    /// The results of the conversational query or event processing.
    #[prost(message, optional, tag="2")]
    pub query_result: ::core::option::Option<super::nlu::DetectIntentResponse>,
}
/// Message for running a web scraper job.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RunScraperRequest {
    /// List of project IDs to run the scraper on.
    #[prost(string, repeated, tag="1")]
    pub project_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// Message containing the response for running a web scraper job.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RunScraperResponse {
    /// List of scraper containers running the jobs.
    #[prost(message, repeated, tag="1")]
    pub scraper_containers: ::prost::alloc::vec::Vec<run_scraper_response::ScraperContainer>,
}
/// Nested message and enum types in `RunScraperResponse`.
pub mod run_scraper_response {
    /// Message representing a scraper container.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct ScraperContainer {
        /// Name of the Docker container running the job.
        #[prost(string, tag="1")]
        pub container_name: ::prost::alloc::string::String,
        /// ID of the Docker container running the scraping job.
        #[prost(string, tag="2")]
        pub container_id: ::prost::alloc::string::String,
    }
}
/// Message containing the response for running a training job.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RunTrainingResponse {
    /// F1 score as a response of the training.
    #[prost(float, tag="1")]
    pub f1: f32,
    /// Accuracy as a response of the training.
    #[prost(float, tag="2")]
    pub accuracy: f32,
}
/// Message for defining URL filters to include and exclude from the scraping process.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UrlFilter {
    /// Optional. List of allowed values for the metadata field <code>&apos;url&apos;</code>.
    #[prost(string, repeated, tag="1")]
    pub allowed_values: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Optional. Regular expression that must be matched by the metadata.
    #[prost(string, tag="2")]
    pub regex_filter_include: ::prost::alloc::string::String,
    /// Optional. Regular expression that must not be matched by the metadata.
    #[prost(string, tag="3")]
    pub regex_filter_exclude: ::prost::alloc::string::String,
}
/// Message containing the response for checking the server state.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetServerStateResponse {
    /// Indicates whether the server is ready to accept requests.
    #[prost(bool, tag="1")]
    pub server_is_ready: bool,
}
/// Message for listing project IDs in the response.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListProjectIdsResponse {
    /// List of project IDs.
    #[prost(string, repeated, tag="1")]
    pub project_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// Message for requesting the configuration of a specific project.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetProjectConfigRequest {
    /// The ID of the project for which to retrieve the configuration.
    #[prost(string, tag="1")]
    pub project_id: ::prost::alloc::string::String,
}
/// Message containing the response for getting the configuration of a project.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetProjectConfigResponse {
    /// Serialized configuration of the project.
    #[prost(string, tag="1")]
    pub config_serialized: ::prost::alloc::string::String,
}
/// Message for requesting a database update for specific projects.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateDatabaseRequest {
    /// List of project IDs for which to update the database.
    #[prost(string, repeated, tag="1")]
    pub project_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// Message containing the response for updating the database of specific projects.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateDatabaseResponse {
    /// List of error messages encountered during the database update.
    #[prost(string, repeated, tag="1")]
    pub error_messages: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
include!("ondewo.qa.tonic.rs");
// @@protoc_insertion_point(module)
