// @generated
// This file is @generated by prost-build.
// /////////////////////////
// Configuration Message //
// /////////////////////////

/// <p>Configuration for a request to transcribe audio</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TranscribeRequestConfig {
    /// Required. id of the pipeline (model setup) that will generate audio
    #[prost(string, tag="1")]
    pub s2t_pipeline_id: ::prost::alloc::string::String,
    /// Optional. decoding type
    #[prost(enumeration="Decoding", tag="2")]
    pub decoding: i32,
    /// Optional. Specify language of transcription to return
    #[prost(string, optional, tag="9")]
    pub language: ::core::option::Option<::prost::alloc::string::String>,
    /// Optional. Specify task of s2t model, e.g. &apos;transcribe&apos; and &apos;translate&apos;
    #[prost(string, optional, tag="10")]
    pub task: ::core::option::Option<::prost::alloc::string::String>,
    /// Optional. <code>s2t_service_config</code> provides the configuration of the service such as API key, bearer tokens, JWT,
    /// and other header information as key value pairs, e.g., <pre><code>MY_API_KEY=&apos;LKJDIFe244LKJOI&apos;</code></pre>
    /// For Amazon S2T service, the following arguments should be passed in form of a dict:
    /// <ul>
    ///    <li><code>aws_access_key_id</code> (required) Access key id to access Amazon Web Service.</li>
    ///    <li><code>aws_secret_access_key</code> (required) Secret access key to access Amazon Web Service.</li>
    ///    <li><code>region</code> (required) Region name of Amazon Server.</li>
    /// </ul>
    /// Example: <code>s2t_config_service={&apos;aws_access_key_id&apos;: &apos;YOUR_AWS_ACCESS_KEY_ID&apos;, &apos;aws_secret_access_key&apos;:
    /// &apos;YOUR_AWS_SECRET_ACCESS_KEY&apos;, &apos;region&apos;: &apos;YOUR_AMAZON_SERVER_REGION_NAME&apos;}</code>
    /// For Deepgram S2T service, the following argument should be passed in form of a dict:
    /// <ul>
    ///    <li><code>api_key</code> (required) API key of Deepgram account to access Deepgram S2T service.</li>
    /// </ul>
    /// Example: <code>s2t_config_service={&apos;api_key&apos;: &apos;YOUR_DEEPGRAM_API_KEY&apos;}</code>
    /// <br>
    /// For Google cloud S2T service, the following arguments should be passed in form of a dict:
    /// <ul>
    ///    <li><code>api_key</code> (required) API key of Google cloud to access its S2T service.</li>
    ///    <li><code>api_endpoint</code> (optional) Regional API endpoint of Google cloud S2T service. (Defaults to
    /// &apos;eu-speech.googleapis.com&apos;)</li>
    /// </ul>
    /// Example: <code>s2t_config_service={&apos;api_key&apos;: &apos;YOUR_GOOGLE_CLOUD_API_KEY&apos;, &apos;api_endpoint&apos;: &apos;YOUR_GOOGLE_CLOUD_API_ENDPOINT&apos;}</code>
    /// For Microsoft Azure S2T service, the following arguments should be passed in form of a dict:
    /// <ul>
    ///    <li><code>subscription_key</code> (required) Subscription key to access Microsoft Azure Service.</li>
    ///    <li><code>region</code> (required) Region name of Microsoft Azure Server.</li>
    /// </ul>
    /// Example: <code>s2t_config_service={&apos;subscription_key&apos;: &apos;YOUR_MICROSOFT_AZURE_SUBSCRIPTION_KEY&apos;, &apos;region&apos;:
    /// &apos;YOUR_MICROSOFT_AZURE_SERVER_REGION_NAME&apos;}</code>
    /// Note: ondewo-s2t will raise an error if you don&apos;t pass any of the required arguments above.
    #[prost(message, optional, tag="11")]
    pub s2t_service_config: ::core::option::Option<::prost_types::Struct>,
    /// Optional. Defines the cloud provider&apos;s specific configuration for using speech to text cloud services.
    /// The default value is None.
    #[prost(message, optional, tag="12")]
    pub s2t_cloud_provider_config: ::core::option::Option<S2tCloudProviderConfig>,
    /// Optional. Language model name for decoding (in none, default will be taken from config file)
    #[prost(oneof="transcribe_request_config::OneofLanguageModelName", tags="3")]
    pub oneof_language_model_name: ::core::option::Option<transcribe_request_config::OneofLanguageModelName>,
    /// Optional. Configuration of spelling correction and normalization
    #[prost(oneof="transcribe_request_config::OneofPostProcessing", tags="4")]
    pub oneof_post_processing: ::core::option::Option<transcribe_request_config::OneofPostProcessing>,
    /// Optional. Configuration for the detection of utterances
    #[prost(oneof="transcribe_request_config::OneofUtteranceDetection", tags="5")]
    pub oneof_utterance_detection: ::core::option::Option<transcribe_request_config::OneofUtteranceDetection>,
    /// Optional. Which method to be used for voice activity detection
    #[prost(oneof="transcribe_request_config::VoiceActivityDetection", tags="6")]
    pub voice_activity_detection: ::core::option::Option<transcribe_request_config::VoiceActivityDetection>,
    /// Optional. Specify which data to return
    #[prost(oneof="transcribe_request_config::OneofReturnOptions", tags="8")]
    pub oneof_return_options: ::core::option::Option<transcribe_request_config::OneofReturnOptions>,
}
/// Nested message and enum types in `TranscribeRequestConfig`.
pub mod transcribe_request_config {
    /// Optional. Language model name for decoding (in none, default will be taken from config file)
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum OneofLanguageModelName {
        /// Name of the language model
        #[prost(string, tag="3")]
        LanguageModelName(::prost::alloc::string::String),
    }
    /// Optional. Configuration of spelling correction and normalization
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum OneofPostProcessing {
        /// The postprocessing options
        #[prost(message, tag="4")]
        PostProcessing(super::PostProcessingOptions),
    }
    /// Optional. Configuration for the detection of utterances
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum OneofUtteranceDetection {
        /// The utterance detection options
        #[prost(message, tag="5")]
        UtteranceDetection(super::UtteranceDetectionOptions),
    }
    /// Optional. Which method to be used for voice activity detection
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum VoiceActivityDetection {
        /// Voice activity detection with pyannote
        #[prost(message, tag="6")]
        Pyannote(super::Pyannote),
    }
    /// Optional. Specify which data to return
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum OneofReturnOptions {
        /// The transcribe return options
        #[prost(message, tag="8")]
        ReturnOptions(super::TranscriptionReturnOptions),
    }
}
/// <p>Configuration for cloud provider settings for Speech-to-Text (S2T).</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct S2tCloudProviderConfig {
    /// Optional. Configuration for Amazon web service speech-to-text provider.
    #[prost(message, optional, tag="1")]
    pub s2t_cloud_provider_config_amazon: ::core::option::Option<S2tCloudProviderConfigAmazon>,
    /// Optional. Configuration for DeepGram speech-to-text provider.
    #[prost(message, optional, tag="2")]
    pub s2t_cloud_provider_config_deepgram: ::core::option::Option<S2tCloudProviderConfigDeepgram>,
    /// Optional. Configuration for Google speech-to-text provider.
    #[prost(message, optional, tag="3")]
    pub s2t_cloud_provider_config_google: ::core::option::Option<S2tCloudProviderConfigGoogle>,
    /// Optional. Configuration for Microsoft Azure speech-to-text provider.
    #[prost(message, optional, tag="4")]
    pub s2t_cloud_provider_config_microsoft: ::core::option::Option<S2tCloudProviderConfigMicrosoft>,
}
/// <p>Configuration details specific to the Amazon web service speech-to-text provider.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct S2tCloudProviderConfigAmazon {
    /// Optional. Enables or disables <code>partial_results_stabilization</code> feature. More details at:
    /// <a href="<https://docs.aws.amazon.com/transcribe/latest/dg/streaming-partial-results.html#streaming-partial-result-stabilization">https://docs.aws.amazon.com/transcribe/latest/dg/streaming-partial-results.html#streaming-partial-result-stabilization</a>>
    #[prost(bool, optional, tag="1")]
    pub enable_partial_results_stabilization: ::core::option::Option<bool>,
    /// Optional. You can use this field to set the stability level of the transcription results.
    /// A higher stability level means that the transcription results are less likely to change.
    /// Higher stability levels can come with lower overall transcription accuracy.
    /// Acceptable values: \[&quot;low&quot;, &quot;medium&quot;, &quot;high&quot;\]. Defaults to &quot;high&quot; if not set explicitly. More details at:
    /// <a href="<https://aws.amazon.com/blogs/machine-learning/amazon-transcribe-now-supports-partial-results-stabilization-for-streaming-audio/">https://aws.amazon.com/blogs/machine-learning/amazon-transcribe-now-supports-partial-results-stabilization-for-streaming-audio/</a>>
    #[prost(string, optional, tag="2")]
    pub partial_results_stability: ::core::option::Option<::prost::alloc::string::String>,
    /// Optional. The name of your customize language model you want to use.
    /// More details at: <a href="<https://docs.aws.amazon.com/transcribe/latest/dg/custom-language-models.html">https://docs.aws.amazon.com/transcribe/latest/dg/custom-language-models.html</a>>
    #[prost(string, optional, tag="3")]
    pub language_model_name: ::core::option::Option<::prost::alloc::string::String>,
    /// Optional. The name of your customize vocabulary you want to use.
    /// More details at: <a href="<https://docs.aws.amazon.com/transcribe/latest/dg/custom-vocabulary.html">https://docs.aws.amazon.com/transcribe/latest/dg/custom-vocabulary.html</a>>
    #[prost(string, optional, tag="4")]
    pub vocabulary_name: ::core::option::Option<::prost::alloc::string::String>,
}
/// <p>Configuration details specific to the Deepgram speech-to-text provider.</p>
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct S2tCloudProviderConfigDeepgram {
    /// Optional. Enables or disables <code>punctuate</code> feature of Deepgram to add punctuations to the resulted transcript.
    /// More details at: <a href="<https://developers.deepgram.com/docs/punctuation">https://developers.deepgram.com/docs/punctuation</a>>
    #[prost(bool, optional, tag="1")]
    pub punctuate: ::core::option::Option<bool>,
    /// Optional. Enables or disables <code>smart_format</code> feature of Deepgram transcription result to improve readability.
    /// More details at: <a href="<https://developers.deepgram.com/docs/smart-format">https://developers.deepgram.com/docs/smart-format</a>>
    #[prost(bool, optional, tag="2")]
    pub smart_format: ::core::option::Option<bool>,
    /// Optional. Enables or disables <code>numerals</code> feature of Deepgram to convert numbers to numeric form in the resulted
    /// transcript. More details at: <a href="<https://developers.deepgram.com/docs/numerals">https://developers.deepgram.com/docs/numerals</a>>
    #[prost(bool, optional, tag="3")]
    pub numerals: ::core::option::Option<bool>,
    /// Optional. Enables or disables <code>measurements</code> feature of Deepgram to convert measurement units (i.e. Kilogram)
    /// to abbreviated form (i.e. Kg) in the resulted transcript.
    /// More details at: <a href="<https://developers.deepgram.com/docs/measurements">https://developers.deepgram.com/docs/measurements</a>>
    #[prost(bool, optional, tag="4")]
    pub measurements: ::core::option::Option<bool>,
    /// Optional. Enables or disables <code>dictation</code> feature of Deepgram to convert spoken dictation commands into their
    /// corresponding punctuation marks. More details at: <a href="<https://developers.deepgram.com/docs/dictation">https://developers.deepgram.com/docs/dictation</a>>
    #[prost(bool, optional, tag="5")]
    pub dictation: ::core::option::Option<bool>,
}
/// <p>Configuration details specific to the Google speech-to-text provider.</p>
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct S2tCloudProviderConfigGoogle {
    /// Optional. Enables or disables <code>automatic_punctuation</code> feature of Google s2t to add punctuations to the resulted
    /// transcript. More details at: <a href="<https://cloud.google.com/speech-to-text/docs/automatic-punctuation">https://cloud.google.com/speech-to-text/docs/automatic-punctuation</a>>
    #[prost(bool, optional, tag="1")]
    pub enable_automatic_punctuation: ::core::option::Option<bool>,
    /// Optional. Enables or disables <code>word_time_offsets</code> feature of Google s2t to add word-level timestamps (time-offset)
    /// to the resulted transcript. More details at: <a href="<https://cloud.google.com/speech-to-text/docs/async-time-offsets">https://cloud.google.com/speech-to-text/docs/async-time-offsets</a>>
    #[prost(bool, optional, tag="2")]
    pub enable_word_time_offsets: ::core::option::Option<bool>,
    /// Optional. Enables or disables <code>word_confidence</code> feature of Google s2t to add word-level confidence scores
    /// to the resulted transcript. More details at: <a href="<https://cloud.google.com/speech-to-text/docs/word-confidence">https://cloud.google.com/speech-to-text/docs/word-confidence</a>>
    #[prost(bool, optional, tag="3")]
    pub enable_word_confidence: ::core::option::Option<bool>,
    /// Optional. Enables or disables <code>transcript_normalization</code> feature of Google s2t to automatically
    /// replace parts of the transcript with phrases of your choosing. More details at:
    /// <a href="<https://cloud.google.com/speech-to-text/v2/docs/reference/rpc/google.cloud.speech.v2#transcriptnormalization">https://cloud.google.com/speech-to-text/v2/docs/reference/rpc/google.cloud.speech.v2#transcriptnormalization</a>>
    #[prost(bool, optional, tag="4")]
    pub transcript_normalization: ::core::option::Option<bool>,
    /// Optional. Maximum number of recognition hypotheses to be returned, may be returned fewer than <code>max_alternatives</code>.
    /// Valid values are 0-30. A value of 0 or 1 will return a maximum of one. If omitted, will return a maximum of one.
    #[prost(int32, optional, tag="5")]
    pub max_alternatives: ::core::option::Option<i32>,
}
/// <p>Configuration details specific to the Microsoft Azure speech-to-text provider.</p>
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct S2tCloudProviderConfigMicrosoft {
    /// Optional. Enables or disables the Microsoft Azure fast transcription API. It is faster than SDK but is in
    /// preview version.
    /// More details at: <a href="<https://learn.microsoft.com/en-us/azure/ai-services/speech-service/fast-transcription-create">https://learn.microsoft.com/en-us/azure/ai-services/speech-service/fast-transcription-create</a>>
    #[prost(bool, optional, tag="1")]
    pub use_fast_transcription_api: ::core::option::Option<bool>,
    /// Optional. Enables or disables the <code>detailed</code> format for the result of Microsoft Azure s2t service
    /// to add timestamps and confidences to the resulted transcript.
    #[prost(bool, optional, tag="2")]
    pub use_detailed_output_format: ::core::option::Option<bool>,
}
/// <p>Configuration of the return values of a transcribe request</p>
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TranscriptionReturnOptions {
    /// should server make response indicating that the beginning of the speech was detected
    #[prost(bool, tag="1")]
    pub return_start_of_speech: bool,
    /// should s2t server return audio bytes of transcribed utterance
    #[prost(bool, tag="2")]
    pub return_audio: bool,
    /// Whether or not to return confidence scores
    #[prost(bool, tag="3")]
    pub return_confidence_score: bool,
    /// Whether or not to return alternative results from beam-search
    #[prost(bool, tag="4")]
    pub return_alternative_transcriptions: bool,
    /// Optional. Number of alternative transcriptions results from beam-search or greedy-search
    #[prost(int32, tag="5")]
    pub return_alternative_transcriptions_nr: i32,
    /// Whether or not to return alternative results from beam-search
    #[prost(bool, tag="6")]
    pub return_alternative_words: bool,
    /// Optional. Number of alternative words to results
    #[prost(int32, tag="7")]
    pub return_alternative_words_nr: i32,
    /// Optional. Whether or not to return timestamps of start and end of the words. Only used in TranscribeFile.
    #[prost(bool, tag="8")]
    pub return_word_timing: bool,
}
/// <p>Configuration of the options to detect utterances</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UtteranceDetectionOptions {
    /// if time between audio chunks exceeds next_chunk_timeout, stream will be stopped
    #[prost(float, tag="2")]
    pub next_chunk_timeout: f32,
    /// Whether or not to transcribe unfinished utterances.
    #[prost(oneof="utterance_detection_options::OneofTranscribeNotFinal", tags="1")]
    pub oneof_transcribe_not_final: ::core::option::Option<utterance_detection_options::OneofTranscribeNotFinal>,
    /// Optional. Configuration for the turn-detection in utterances
    #[prost(oneof="utterance_detection_options::OneofTurnDetection", tags="3")]
    pub oneof_turn_detection: ::core::option::Option<utterance_detection_options::OneofTurnDetection>,
}
/// Nested message and enum types in `UtteranceDetectionOptions`.
pub mod utterance_detection_options {
    /// Whether or not to transcribe unfinished utterances.
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum OneofTranscribeNotFinal {
        /// Return also immediate transcription results
        #[prost(bool, tag="1")]
        TranscribeNotFinal(bool),
    }
    /// Optional. Configuration for the turn-detection in utterances
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum OneofTurnDetection {
        /// The turn detection options
        #[prost(message, tag="3")]
        TurnDetection(super::TurnDetectionOptions),
    }
}
/// <p>Configuration of the post-processing options</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PostProcessingOptions {
    /// Whether to use spelling correction
    #[prost(bool, tag="1")]
    pub spelling_correction: bool,
    /// Whether to disable normalization
    #[prost(bool, tag="2")]
    pub normalize: bool,
    /// Post-processing configuration specifying the active post-processors in the pipeline, as well as their individual
    /// configuration. If not set, all values are replaced by the ones in current pipeline.
    #[prost(message, optional, tag="3")]
    pub config: ::core::option::Option<PostProcessing>,
    /// Whether to disable LLM post-processing
    #[prost(bool, tag="4")]
    pub llm_post_processing: bool,
}
// /////////////////////////
//   TRANSCRIPTION TYPE  //
// /////////////////////////

/// <p>The transcription message</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transcription {
    /// The transcribed text
    #[prost(string, tag="1")]
    pub transcription: ::prost::alloc::string::String,
    /// The corresponding confidence score. The confidence estimate between 0.0 and 1.0. A higher number
    /// indicates an estimated greater likelihood that the recognized words are correct.
    #[prost(float, tag="2")]
    pub confidence_score: f32,
    /// List of the words of transcription with their confidence scores and probable alternatives
    #[prost(message, repeated, tag="3")]
    pub words: ::prost::alloc::vec::Vec<WordDetail>,
    /// List of alternative transcriptions, confidence scores, words timings and alternative words
    #[prost(message, repeated, tag="4")]
    pub alternatives: ::prost::alloc::vec::Vec<TranscriptionAlternative>,
}
/// <p>The alternative transcription message</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TranscriptionAlternative {
    /// The alternative transcribed text
    #[prost(string, tag="1")]
    pub transcript: ::prost::alloc::string::String,
    /// The corresponding confidence score to the alternative transcript.
    #[prost(float, tag="2")]
    pub confidence: f32,
    /// A list of word-specific information for each recognized word, including word timings, confidence score of
    /// the word and alternative words.
    #[prost(message, repeated, tag="3")]
    pub words: ::prost::alloc::vec::Vec<WordDetail>,
}
/// <p>WordDetail provides word-specific information for recognized words.</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WordDetail {
    /// The start time of the spoken word relative to the beginning of the audio.
    /// The accuracy of the time offset can vary, and this is an experimental feature.
    #[prost(float, tag="1")]
    pub start_time: f32,
    /// The end time of the spoken word relative to the beginning of the audio.
    /// The accuracy of the time offset can vary, and this is an experimental feature.
    #[prost(float, tag="2")]
    pub end_time: f32,
    /// The recognized word corresponding to this set of information.
    #[prost(string, tag="3")]
    pub word: ::prost::alloc::string::String,
    /// The corresponding confidence score to the word.
    #[prost(float, tag="4")]
    pub confidence: f32,
    /// List of alternative words and confidence scores of each.
    #[prost(message, repeated, tag="5")]
    pub word_alternatives: ::prost::alloc::vec::Vec<WordAlternative>,
}
/// <p>The word alternative message</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WordAlternative {
    /// The recognized word corresponding to this set of information.
    #[prost(string, tag="1")]
    pub word: ::prost::alloc::string::String,
    /// The corresponding confidence score to the alternative word.
    #[prost(float, tag="2")]
    pub confidence: f32,
}
// /////////////////////
// TRANSCRIBE STREAM //
// /////////////////////

/// <p>Request to transcribe an audio stream</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TranscribeStreamRequest {
    /// wav file to transcribe
    #[prost(bytes="vec", tag="1")]
    pub audio_chunk: ::prost::alloc::vec::Vec<u8>,
    /// if it's the final chunk of the stream
    #[prost(bool, tag="2")]
    pub end_of_stream: bool,
    /// The configuration to override the default configuration
    #[prost(message, optional, tag="3")]
    pub config: ::core::option::Option<TranscribeRequestConfig>,
    /// Whether or not to mute the audio signal. Defaults to false.
    #[prost(bool, tag="4")]
    pub mute_audio: bool,
}
/// <p>The response message of a stream transcription</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TranscribeStreamResponse {
    /// List of transcriptions with confidence level
    #[prost(message, repeated, tag="1")]
    pub transcriptions: ::prost::alloc::vec::Vec<Transcription>,
    /// The time the transcription took
    #[prost(float, tag="2")]
    pub time: f32,
    /// Whether or not this transcription is final (transcribed texts might change if transcription is
    /// started before the end of an utterance).
    #[prost(bool, tag="3")]
    pub r#final: bool,
    /// is audio bytes of the utterance in response
    #[prost(bool, tag="4")]
    pub return_audio: bool,
    /// audio bytes of the transcribed utterance
    #[prost(bytes="vec", tag="5")]
    pub audio: ::prost::alloc::vec::Vec<u8>,
    /// is it a start of the utterance
    #[prost(bool, tag="6")]
    pub utterance_start: bool,
    /// id of the transcribed audio file
    #[prost(string, tag="7")]
    pub audio_uuid: ::prost::alloc::string::String,
    /// The configuration to override the default configuration
    #[prost(oneof="transcribe_stream_response::OneofConfig", tags="8")]
    pub oneof_config: ::core::option::Option<transcribe_stream_response::OneofConfig>,
}
/// Nested message and enum types in `TranscribeStreamResponse`.
pub mod transcribe_stream_response {
    /// The configuration to override the default configuration
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum OneofConfig {
        /// The configuration for the transcription
        #[prost(message, tag="8")]
        Config(super::TranscribeRequestConfig),
    }
}
// ///////////////////
// TRANSCRIBE FILE //
// ///////////////////

/// <p>A request to transcribe an audio file</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TranscribeFileRequest {
    /// wav file to transcribe
    #[prost(bytes="vec", tag="1")]
    pub audio_file: ::prost::alloc::vec::Vec<u8>,
    /// The configuration to override the default configuration
    #[prost(message, optional, tag="2")]
    pub config: ::core::option::Option<TranscribeRequestConfig>,
}
/// <p>The response message for a transcribe file request</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TranscribeFileResponse {
    /// List of transcriptions with confidence level
    #[prost(message, repeated, tag="1")]
    pub transcriptions: ::prost::alloc::vec::Vec<Transcription>,
    /// The time the transcription took
    #[prost(float, tag="2")]
    pub time: f32,
    /// id of the transcribed audio file
    #[prost(string, tag="3")]
    pub audio_uuid: ::prost::alloc::string::String,
}
// ////////////////////
// GET S2T PIPELINE //
// ////////////////////

/// <p>The pipeline id for a specific pipeline configuration</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct S2tPipelineId {
    /// id of the model that will generate audio
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
// //////////////////////
// LIST S2T PIPELINES //
// //////////////////////

/// <p>Request to list all speech-to-text pipelines. Optionally also filter criteria can be set</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListS2tPipelinesRequest {
    /// Filter for languages
    #[prost(string, repeated, tag="1")]
    pub languages: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Filter for pipeline owners
    #[prost(string, repeated, tag="2")]
    pub pipeline_owners: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Filter for domains
    #[prost(string, repeated, tag="3")]
    pub domains: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// If true, return only registered pipelines.
    /// Default false: return registered and persisted (from config files) configs.
    #[prost(bool, tag="4")]
    pub registered_only: bool,
}
/// <p>ListS2tPipelinesResponse is used to return a list of all speech-to-text pipelines.</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListS2tPipelinesResponse {
    /// A list of <code>Speech2TextConfig</code> message instances containing the configuration of each pipeline.
    /// Example: [{id: &quot;pipeline_1&quot;, description: {language: &quot;en&quot;}, active: true, ...}, {id: &quot;pipeline_2&quot;,
    /// description: {language: &quot;fr&quot;}, active: true, ...}]
    #[prost(message, repeated, tag="1")]
    pub pipeline_configs: ::prost::alloc::vec::Vec<Speech2TextConfig>,
}
// //////////////////////
// LIST S2T LANGUAGES //
// //////////////////////

/// <p>ListS2tLanguagesRequest is used to request a list of available languages. Optionally, filters can be set.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListS2tLanguagesRequest {
    /// Filter for domains.  Example: \[&quot;medical&quot;, &quot;finance&quot;\]
    #[prost(string, repeated, tag="1")]
    pub domains: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Filter for pipeline owners.
    /// Example: \[&quot;ondewo&quot;, &quot;partner_company&quot;\]
    #[prost(string, repeated, tag="2")]
    pub pipeline_owners: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// <p>Response message to list available languages</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListS2tLanguagesResponse {
    /// available languages
    #[prost(string, repeated, tag="1")]
    pub languages: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
// ////////////////////
// LIST S2T DOMAINS //
// ////////////////////

/// <p>Request message to list available domains. Optionally also filters can be set.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListS2tDomainsRequest {
    /// Filter for languages
    #[prost(string, repeated, tag="1")]
    pub languages: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Filter for pipeline owner
    #[prost(string, repeated, tag="2")]
    pub pipeline_owners: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// <p>Response message to list available domains</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListS2tDomainsResponse {
    /// domains available. Example: \[&quot;medical&quot;, &quot;finance&quot;\]
    #[prost(string, repeated, tag="1")]
    pub domains: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
// ////////////////////
// GET SERVICE INFO //
// ////////////////////

/// <p>S2tGetServiceInfoResponse is used to return version information about the speech-to-text service.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct S2tGetServiceInfoResponse {
    /// Version number based on semantic versioning, e.g. &quot;4.2.0&quot;.
    #[prost(string, tag="1")]
    pub version: ::prost::alloc::string::String,
}
// /////////////////////////////////
// SPEECH-2-TEXT PIPELINE CONFIG //
// /////////////////////////////////

/// <p>Speech2TextConfig is a configuration message for the speech-to-text pipeline</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Speech2TextConfig {
    /// Unique identifier for the configuration.
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    /// Description of the speech-to-text system.
    #[prost(message, optional, tag="2")]
    pub description: ::core::option::Option<S2tDescription>,
    /// Indicates if the configuration is active.
    #[prost(bool, tag="3")]
    pub active: bool,
    /// Configuration for inference models.
    #[prost(message, optional, tag="4")]
    pub inference: ::core::option::Option<S2tInference>,
    /// Configuration for the streaming server.
    #[prost(message, optional, tag="5")]
    pub streaming_server: ::core::option::Option<StreamingServer>,
    /// Configuration for voice activity detection.
    #[prost(message, optional, tag="6")]
    pub voice_activity_detection: ::core::option::Option<VoiceActivityDetection>,
    /// Configuration for post-processing.
    #[prost(message, optional, tag="7")]
    pub post_processing: ::core::option::Option<PostProcessing>,
    /// Configuration for logging.
    #[prost(message, optional, tag="8")]
    pub logging: ::core::option::Option<Logging>,
}
/// <p>S2tDescription contains descriptive information about the speech-to-text pipeline.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct S2tDescription {
    /// Language of the speech-to-text system.
    #[prost(string, tag="1")]
    pub language: ::prost::alloc::string::String,
    /// Owner of the pipeline.
    #[prost(string, tag="2")]
    pub pipeline_owner: ::prost::alloc::string::String,
    /// Domain of the speech-to-text system.
    #[prost(string, tag="3")]
    pub domain: ::prost::alloc::string::String,
    /// Comments about the system.
    #[prost(string, tag="4")]
    pub comments: ::prost::alloc::string::String,
}
/// <p>S2tInference contains information about inference models used in the speech-to-text pipeline.</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct S2tInference {
    /// Configuration for the acoustic models.
    #[prost(message, optional, tag="1")]
    pub acoustic_models: ::core::option::Option<AcousticModels>,
    /// Configuration for the language models.
    #[prost(message, optional, tag="2")]
    pub language_models: ::core::option::Option<LanguageModels>,
    /// Configuration for the inference backend.
    #[prost(enumeration="InferenceBackend", tag="3")]
    pub inference_backend: i32,
}
/// <p>AcousticModels contains information about different types of acoustic models.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AcousticModels {
    /// Type of the acoustic model.
    #[prost(string, tag="1")]
    pub r#type: ::prost::alloc::string::String,
    /// Configuration for the Wav2Vec model.
    #[prost(message, optional, tag="2")]
    pub wav2vec: ::core::option::Option<Wav2Vec>,
    /// Configuration for the Wav2Vec model using Triton.
    #[prost(message, optional, tag="3")]
    pub wav2vec_triton: ::core::option::Option<Wav2VecTriton>,
    /// Configuration for the Whisper model.
    #[prost(message, optional, tag="4")]
    pub whisper: ::core::option::Option<Whisper>,
    /// Configuration for the Whisper model using Triton.
    #[prost(message, optional, tag="5")]
    pub whisper_triton: ::core::option::Option<WhisperTriton>,
    /// Amazon web service cloud service inference settings.
    #[prost(message, optional, tag="6")]
    pub s2t_cloud_service_amazon: ::core::option::Option<S2tCloudServiceAmazon>,
    /// Deepgram cloud service inference settings.
    #[prost(message, optional, tag="7")]
    pub s2t_cloud_service_deepgram: ::core::option::Option<S2tCloudServiceDeepgram>,
    /// Google cloud service inference settings.
    #[prost(message, optional, tag="8")]
    pub s2t_cloud_service_google: ::core::option::Option<S2tCloudServiceGoogle>,
    /// Microsoft Azure cloud service inference settings.
    #[prost(message, optional, tag="9")]
    pub s2t_cloud_service_microsoft: ::core::option::Option<S2tCloudServiceMicrosoft>,
    /// Configuration for the Parakeet model.
    #[prost(message, optional, tag="10")]
    pub parakeet: ::core::option::Option<Parakeet>,
}
/// <p>S2tCloudServiceAmazon message contains settings for the Amazon web service Cloud service inference.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct S2tCloudServiceAmazon {
    /// Language of the audio to transcribe by Amazon web service s2t cloud service. It should be 4-letter language code
    /// (BCP-47) e.g. &apos;en-US&apos; or &apos;de-DE&apos;.
    #[prost(string, tag="1")]
    pub language: ::prost::alloc::string::String,
    /// Specifies if streaming mode of Amazon web service speech to text is available for the selected language,
    /// otherwise batch mode transcription is used. See the list of languages and available transcription modes at:
    /// <a href="<https://docs.aws.amazon.com/transcribe/latest/dg/supported-languages.html">https://docs.aws.amazon.com/transcribe/latest/dg/supported-languages.html</a>>
    #[prost(bool, tag="2")]
    pub streaming_available: bool,
    /// Enables or disables <code>partial_results_stabilization</code> feature. More details at:
    /// <a href="<https://docs.aws.amazon.com/transcribe/latest/dg/streaming-partial-results.html#streaming-partial-result-stabilization">https://docs.aws.amazon.com/transcribe/latest/dg/streaming-partial-results.html#streaming-partial-result-stabilization</a>>
    #[prost(bool, tag="3")]
    pub enable_partial_results_stabilization: bool,
    /// You can use this field to set the stability level of the transcription results.
    /// A higher stability level means that the transcription results are less likely to change.
    /// Higher stability levels can come with lower overall transcription accuracy.
    /// Defaults to &quot;high&quot; if not set explicitly.
    #[prost(string, tag="4")]
    pub partial_results_stability: ::prost::alloc::string::String,
    /// The name of your customize language model you want to use.
    /// More details at: <a href="<https://docs.aws.amazon.com/transcribe/latest/dg/custom-language-models.html">https://docs.aws.amazon.com/transcribe/latest/dg/custom-language-models.html</a>>
    #[prost(string, tag="5")]
    pub language_model_name: ::prost::alloc::string::String,
    /// The name of your customize vocabulary you want to use.
    /// More details at: <a href="<https://docs.aws.amazon.com/transcribe/latest/dg/custom-vocabulary.html">https://docs.aws.amazon.com/transcribe/latest/dg/custom-vocabulary.html</a>>
    #[prost(string, tag="6")]
    pub vocabulary_name: ::prost::alloc::string::String,
}
/// <p>S2tCloudServiceDeepgram message contains settings for the Deepgram Cloud service inference.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct S2tCloudServiceDeepgram {
    /// Model name from one of the speech-to-text models provided by Deepgram for the desired use-case.
    /// Provided model names and details at: <a href="<https://developers.deepgram.com/docs/model">https://developers.deepgram.com/docs/model</a>>
    #[prost(string, tag="1")]
    pub model_name: ::prost::alloc::string::String,
    /// Language of the audio to transcribe by Deepgram s2t cloud service. It should be 4-letter language code
    /// (BCP-47) e.g. &apos;en-US&apos; or &apos;de-DE&apos;.
    #[prost(string, tag="2")]
    pub language: ::prost::alloc::string::String,
    /// Enables or disables <code>punctuate</code> feature of Deepgram to add punctuations to the resulted transcript.
    /// More details at: <a href="<https://developers.deepgram.com/docs/punctuation">https://developers.deepgram.com/docs/punctuation</a>>
    #[prost(bool, tag="3")]
    pub punctuate: bool,
    /// Enables or disables <code>smart_format</code> feature of Deepgram transcription result to improve readability.
    /// More details at: <a href="<https://developers.deepgram.com/docs/smart-format">https://developers.deepgram.com/docs/smart-format</a>>
    #[prost(bool, tag="4")]
    pub smart_format: bool,
    /// Enables or disables <code>numerals</code> feature of Deepgram to convert numbers to numeric form in the resulted transcript.
    /// More details at: <a href="<https://developers.deepgram.com/docs/numerals">https://developers.deepgram.com/docs/numerals</a>>
    #[prost(bool, tag="5")]
    pub numerals: bool,
    /// Enables or disables <code>measurements</code> feature of Deepgram to convert measurement units (i.e. Kilogram)
    /// to abbreviated form (i.e. Kg) in the resulted transcript.
    /// More details at: <a href="<https://developers.deepgram.com/docs/measurements">https://developers.deepgram.com/docs/measurements</a>>
    #[prost(bool, tag="6")]
    pub measurements: bool,
    /// Enables or disables <code>dictation</code> feature of Deepgram to convert spoken dictation commands into their corresponding
    /// punctuation marks. More details at: <a href="<https://developers.deepgram.com/docs/dictation">https://developers.deepgram.com/docs/dictation</a>>
    #[prost(bool, tag="7")]
    pub dictation: bool,
}
/// <p>S2tCloudServiceGoogle message contains settings for the Google Cloud service inference.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct S2tCloudServiceGoogle {
    /// Model name from one of the speech-to-text models provided by Google for the desired use-case.
    /// Provided model names and details at: <a href="<https://cloud.google.com/speech-to-text/docs/transcription-model">https://cloud.google.com/speech-to-text/docs/transcription-model</a>>
    #[prost(string, tag="1")]
    pub model_name: ::prost::alloc::string::String,
    /// Language of the audio to transcribe by Google s2t cloud service. It should be 4-letter language code
    /// (BCP-47) e.g. &apos;en-US&apos; or &apos;de-DE&apos;.
    #[prost(string, tag="2")]
    pub language: ::prost::alloc::string::String,
    /// Enables or disables <code>automatic_punctuation</code> feature of Google s2t to add punctuations to the resulted transcript.
    /// More details at: <a href="<https://cloud.google.com/speech-to-text/docs/automatic-punctuation">https://cloud.google.com/speech-to-text/docs/automatic-punctuation</a>>
    #[prost(bool, tag="3")]
    pub enable_automatic_punctuation: bool,
    /// Enables or disables <code>word_time_offsets</code> feature of Google s2t to add word-level timestamps (time-offsets)
    /// to the resulted transcript. More details at: <a href="<https://cloud.google.com/speech-to-text/docs/async-time-offsets">https://cloud.google.com/speech-to-text/docs/async-time-offsets</a>>
    #[prost(bool, tag="4")]
    pub enable_word_time_offsets: bool,
    /// Enables or disables <code>word_confidence</code> feature of Google s2t to add word-level confidence scores
    /// to the resulted transcript. More details at: <a href="<https://cloud.google.com/speech-to-text/docs/word-confidence">https://cloud.google.com/speech-to-text/docs/word-confidence</a>>
    #[prost(bool, tag="5")]
    pub enable_word_confidence: bool,
    /// Enables or disables <code>transcript_normalization</code> feature of Google s2t to automatically
    /// replace parts of the transcript with phrases of your choosing. More details at:
    /// <a href="<https://cloud.google.com/speech-to-text/v2/docs/reference/rpc/google.cloud.speech.v2#transcriptnormalization">https://cloud.google.com/speech-to-text/v2/docs/reference/rpc/google.cloud.speech.v2#transcriptnormalization</a>>
    #[prost(bool, tag="6")]
    pub transcript_normalization: bool,
    /// Maximum number of recognition hypotheses to be returned. The server may return fewer than <code>max_alternatives</code>.
    /// Valid values are 0-30. A value of 0 or 1 will return a maximum of one. If omitted, will return a maximum of one.
    #[prost(int32, tag="7")]
    pub max_alternatives: i32,
}
/// <p>S2tCloudServiceMicrosoft message contains settings for the Microsoft Azure Cloud service inference.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct S2tCloudServiceMicrosoft {
    /// Language of the audio to transcribe by Microsoft Azure s2t cloud service. It should be 4-letter language code
    /// (BCP-47) e.g. &apos;en-US&apos; or &apos;de-DE&apos;.
    #[prost(string, tag="1")]
    pub language: ::prost::alloc::string::String,
    /// Enables or disables the Microsoft Azure fast transcription API. It is faster than SDK but is in preview version.
    /// More details at: <a href="<https://learn.microsoft.com/en-us/azure/ai-services/speech-service/fast-transcription-create">https://learn.microsoft.com/en-us/azure/ai-services/speech-service/fast-transcription-create</a>>
    #[prost(bool, tag="2")]
    pub use_fast_transcription_api: bool,
    /// Enables or disables the <code>detailed</code> format for the result of Microsoft Azure s2t service
    /// to add timestamps and confidences to the resulted transcript.
    #[prost(bool, tag="3")]
    pub use_detailed_output_format: bool,
}
/// <p>Whisper contains information about the Whisper model.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Whisper {
    /// Path to the model.
    #[prost(string, tag="1")]
    pub model_path: ::prost::alloc::string::String,
    /// Indicates if GPU is used.
    #[prost(bool, tag="2")]
    pub use_gpu: bool,
    /// Default language of the model.
    #[prost(string, tag="3")]
    pub language: ::prost::alloc::string::String,
    /// Default task of the model.
    #[prost(string, tag="4")]
    pub task: ::prost::alloc::string::String,
}
/// <p>WhisperTriton contains information about the Whisper model using Triton.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WhisperTriton {
    /// Path to the processor.
    #[prost(string, tag="1")]
    pub processor_path: ::prost::alloc::string::String,
    /// Name of the Triton model.
    #[prost(string, tag="2")]
    pub triton_model_name: ::prost::alloc::string::String,
    /// Version of the Triton model.
    #[prost(string, tag="3")]
    pub triton_model_version: ::prost::alloc::string::String,
    /// Timeout for checking model status.
    #[prost(int64, tag="4")]
    pub check_status_timeout: i64,
    /// Default language of the model.
    #[prost(string, tag="5")]
    pub language: ::prost::alloc::string::String,
    /// Default task of the model. E.g., transcribe, translate, etc.
    #[prost(string, tag="6")]
    pub task: ::prost::alloc::string::String,
    /// Host name of triton inference server that serves the WhisperTriton model
    #[prost(string, tag="7")]
    pub triton_server_host: ::prost::alloc::string::String,
    /// Port number of triton inference server that serves the WhisperTriton model
    #[prost(int64, tag="8")]
    pub triton_server_port: i64,
}
/// <p>Wav2Vec contains information about the Wav2Vec model.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Wav2Vec {
    /// Path to the model.
    #[prost(string, tag="1")]
    pub model_path: ::prost::alloc::string::String,
    /// Indicates if GPU is used.
    #[prost(bool, tag="2")]
    pub use_gpu: bool,
}
/// <p>Wav2VecTriton contains information about the Wav2Vec model using Triton.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Wav2VecTriton {
    /// Path to the processor.
    #[prost(string, tag="1")]
    pub processor_path: ::prost::alloc::string::String,
    /// Name of the Triton model.
    #[prost(string, tag="2")]
    pub triton_model_name: ::prost::alloc::string::String,
    /// Version of the Triton model.
    #[prost(string, tag="3")]
    pub triton_model_version: ::prost::alloc::string::String,
    /// Timeout for checking model status.
    #[prost(int64, tag="4")]
    pub check_status_timeout: i64,
    /// Host name of triton inference server that serves the Wav2VecTriton model
    #[prost(string, tag="5")]
    pub triton_server_host: ::prost::alloc::string::String,
    /// Port number of triton inference server that serves the Wav2VecTriton model
    #[prost(int64, tag="6")]
    pub triton_server_port: i64,
}
/// <p>Parakeet contains information about the Parakeet model.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Parakeet {
    /// Name of the Triton model.
    #[prost(string, tag="1")]
    pub triton_model_name: ::prost::alloc::string::String,
    /// Version of the Triton model.
    #[prost(string, tag="2")]
    pub triton_model_version: ::prost::alloc::string::String,
    /// Timeout for checking model status.
    #[prost(int64, tag="3")]
    pub check_status_timeout: i64,
    /// Host name of triton inference server that serves the Parakeet model
    #[prost(string, tag="4")]
    pub triton_server_host: ::prost::alloc::string::String,
    /// Port number of triton inference server that serves the Parakeet model
    #[prost(int64, tag="5")]
    pub triton_server_port: i64,
}
/// <p>PtFiles contains information about PT files.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PtFiles {
    /// Path to the PT files.
    #[prost(string, tag="1")]
    pub path: ::prost::alloc::string::String,
    /// Step for the PT files.
    #[prost(string, tag="2")]
    pub step: ::prost::alloc::string::String,
}
/// <p>CkptFile contains information about checkpoint files.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CkptFile {
    /// Path to the checkpoint file.
    #[prost(string, tag="1")]
    pub path: ::prost::alloc::string::String,
}
/// <p>LanguageModels contains information about language models.</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LanguageModels {
    /// Path to the directory of language models.
    #[prost(string, tag="1")]
    pub path: ::prost::alloc::string::String,
    /// Beam size for the search algorithm.
    #[prost(int64, tag="2")]
    pub beam_size: i64,
    /// Default language model to be selected if none is given.
    #[prost(string, tag="3")]
    pub default_lm: ::prost::alloc::string::String,
    /// Weight for the language model scorer (alpha).
    #[prost(float, tag="4")]
    pub beam_search_scorer_alpha: f32,
    /// Weight for the word insertion penalty (beta).
    #[prost(float, tag="5")]
    pub beam_search_scorer_beta: f32,
}
/// <p>StreamingServer contains information about the streaming server.</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StreamingServer {
    /// Hostname of the streaming server.
    #[prost(string, tag="1")]
    pub host: ::prost::alloc::string::String,
    /// Port number of the streaming server.
    #[prost(int64, tag="2")]
    pub port: i64,
    /// Output style for the streaming server.
    #[prost(string, tag="3")]
    pub output_style: ::prost::alloc::string::String,
    /// Configuration for streaming speech recognition.
    #[prost(message, optional, tag="4")]
    pub streaming_speech_recognition: ::core::option::Option<StreamingSpeechRecognition>,
}
/// <p>StreamingSpeechRecognition contains information about streaming speech recognition settings.</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StreamingSpeechRecognition {
    /// Indicates whether to transcribe non-final results.
    #[prost(bool, tag="1")]
    pub transcribe_not_final: bool,
    /// Decoding method for speech recognition.
    #[prost(string, tag="2")]
    pub decoding_method: ::prost::alloc::string::String,
    /// Sampling rate for audio input.
    #[prost(int64, tag="3")]
    pub sampling_rate: i64,
    /// Minimum audio chunk size for processing.
    #[prost(int64, tag="4")]
    pub min_audio_chunk_size: i64,
    /// Timeout between audio chunks; if exceeded, the stream will be stopped.
    #[prost(float, tag="5")]
    pub next_chunk_timeout: f32,
    /// Configuration of the options to turn-detection in utterances
    #[prost(message, optional, tag="6")]
    pub turn_detection: ::core::option::Option<TurnDetectionOptions>,
}
/// <p>Configuration of the options to turn-detection in utterances</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TurnDetectionOptions {
    /// Optional. Indicates if the turn-detection feature is active.
    #[prost(bool, optional, tag="1")]
    pub active: ::core::option::Option<bool>,
    /// Optional. Whether to transcribe the whole utterance when turn moment is detected. It is helpful to increase
    /// accuracy of transcriptions in cost of drop in speed. If deactivated, it just transcribe from last short silence
    /// period and concatenates the transcriptions of small audio chunks between tiny silences.
    #[prost(bool, optional, tag="2")]
    pub full_utterance_deployment: ::core::option::Option<bool>,
    /// Optional. System prompt used to guide the turn-detection model.
    #[prost(string, optional, tag="3")]
    pub turn_detection_system_prompt: ::core::option::Option<::prost::alloc::string::String>,
    /// Optional. User prompt used as input to the turn-detection model.
    #[prost(string, optional, tag="4")]
    pub turn_detection_user_prompt: ::core::option::Option<::prost::alloc::string::String>,
    /// Optional. Configuration options for the OpenAI client used for turn detection.
    #[prost(message, optional, tag="5")]
    pub turn_detection_llm_openai_options: ::core::option::Option<OpenaiLlmOptions>,
}
/// <p>Configuration options for OpenAI client chat completion requests used in turn detection and LLM post-processing.</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpenaiLlmOptions {
    /// Optional. The API key used to authenticate with the OpenAI API.
    #[prost(string, optional, tag="1")]
    pub api_key: ::core::option::Option<::prost::alloc::string::String>,
    /// Optional. The organization ID associated with the OpenAI account, used for billing and access control.
    #[prost(string, optional, tag="2")]
    pub organization: ::core::option::Option<::prost::alloc::string::String>,
    /// Optional. The project ID associated with the OpenAI account.
    #[prost(string, optional, tag="3")]
    pub project: ::core::option::Option<::prost::alloc::string::String>,
    /// Optional. The webhook secret used to validate incoming webhook events from OpenAI.
    #[prost(string, optional, tag="4")]
    pub webhook_secret: ::core::option::Option<::prost::alloc::string::String>,
    /// Optional. The base URL for the OpenAI API. Overrides the default endpoint, useful for proxies or
    /// compatible third-party providers.
    #[prost(string, optional, tag="5")]
    pub base_url: ::core::option::Option<::prost::alloc::string::String>,
    /// Optional. The base URL for OpenAI WebSocket connections. Overrides the default WebSocket endpoint.
    #[prost(string, optional, tag="6")]
    pub websocket_base_url: ::core::option::Option<::prost::alloc::string::String>,
    /// Optional. The timeout in seconds for requests to the OpenAI API. Applies to the entire request
    /// lifecycle including connection, sending, and receiving.
    #[prost(float, optional, tag="7")]
    pub timeout: ::core::option::Option<f32>,
    /// Optional. The maximum number of retries to attempt when a request fails due to a transient error.
    /// Defaults to 2.
    #[prost(int32, optional, tag="8")]
    pub max_retries: ::core::option::Option<i32>,
    /// Optional. Default HTTP headers to include with every request to the OpenAI API.
    #[prost(map="string, string", tag="9")]
    pub default_headers: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    /// Optional. Default query parameters to append to every request URL sent to the OpenAI API.
    /// Values can be of any type (string, number, boolean, list), hence the use of Struct.
    #[prost(message, optional, tag="10")]
    pub default_query: ::core::option::Option<::prost_types::Struct>,
    /// Optional. If true, enables strict validation of response payloads returned by the OpenAI API.
    #[prost(bool, optional, tag="11")]
    pub strict_response_validation: ::core::option::Option<bool>,
    /// Required. The name or identifier of the OpenAI model to use for chat completion
    /// (e.g., "gpt-4o", "gpt-4o-mini", "o3").
    #[prost(string, tag="12")]
    pub model: ::prost::alloc::string::String,
    /// Optional. A number between -2.0 and 2.0. Positive values penalize new tokens based on their
    /// existing frequency in the text so far, decreasing the likelihood of the model repeating the same
    /// line verbatim.
    #[prost(float, optional, tag="13")]
    pub frequency_penalty: ::core::option::Option<f32>,
    /// Optional. Modifies the likelihood of specified tokens appearing in the completion. Maps token IDs
    /// (as strings) to bias values from -100 to 100. Mathematically added to the logits before sampling.
    #[prost(map="string, int32", tag="14")]
    pub logit_bias: ::std::collections::HashMap<::prost::alloc::string::String, i32>,
    /// Optional. Whether to return log probabilities of the output tokens. If true, returns the log
    /// probabilities of each output token in the response.
    #[prost(bool, optional, tag="15")]
    pub logprobs: ::core::option::Option<bool>,
    /// Optional. An upper bound for the number of tokens that can be generated for a completion,
    /// including visible output tokens and reasoning tokens.
    #[prost(int32, optional, tag="16")]
    pub max_completion_tokens: ::core::option::Option<i32>,
    /// Optional. The maximum number of tokens that can be generated in the chat completion.
    /// Deprecated in favor of max_completion_tokens.
    #[prost(int32, optional, tag="17")]
    pub max_tokens: ::core::option::Option<i32>,
    /// Optional. Set of 16 key-value pairs that can be attached to an object. This can be useful for storing additional
    /// information about the object in a structured format, and querying for objects via API or the dashboard.
    #[prost(message, optional, tag="18")]
    pub metadata: ::core::option::Option<::prost_types::Struct>,
    /// Optional. The number of chat completion choices to generate for each input message. Note that
    /// costs are multiplied by the number of choices generated.
    #[prost(int32, optional, tag="19")]
    pub n: ::core::option::Option<i32>,
    /// Optional. A number between -2.0 and 2.0. Positive values penalize new tokens based on whether
    /// they have already appeared in the text, increasing the likelihood of the model discussing new topics.
    #[prost(float, optional, tag="20")]
    pub presence_penalty: ::core::option::Option<f32>,
    /// Optional. Used by OpenAI to cache responses for similar requests to optimize your cache hit rates. Replaces the
    /// `user` field. [Learn more](<https://platform.openai.com/docs/guides/prompt-caching>).
    #[prost(string, optional, tag="21")]
    pub prompt_cache_key: ::core::option::Option<::prost::alloc::string::String>,
    /// Optional. Constrains effort on reasoning for
    /// [reasoning models](<https://platform.openai.com/docs/guides/reasoning>). Currently supported values are `none`,
    /// `minimal`, `low`, `medium`, `high`, and `xhigh`. Reducing reasoning effort can result in faster responses and
    /// fewer tokens used on reasoning in a response.
    #[prost(enumeration="ReasoningEffort", optional, tag="22")]
    pub reasoning_effort: ::core::option::Option<i32>,
    /// Optional. If specified, the system will make a best effort to sample deterministically given the
    /// same seed and parameters, enabling reproducible outputs.
    #[prost(int64, optional, tag="23")]
    pub seed: ::core::option::Option<i64>,
    /// Optional. Specifies the processing type used for serving the request.
    /// - If set to 'auto', then the request will be processed with the service tier configured in the Project settings.
    ///    Unless otherwise configured, the Project will use 'default'.
    /// - If set to 'default', then the request will be processed with the standard pricing and performance for the
    ///    selected model.
    /// - If set to '[flex](<https://platform.openai.com/docs/guides/flex-processing>)' or
    ///    '[priority](<https://openai.com/api-priority-processing/>)', then the request will be processed with the
    ///     corresponding service tier.
    /// - When not set, the default behavior is 'auto'.
    /// When the `service_tier` parameter is set, the response body will include the `service_tier` value based on the
    /// processing mode actually used to serve the request. This response value may be different from the value set in
    /// the parameter.
    #[prost(enumeration="ServiceTier", optional, tag="24")]
    pub service_tier: ::core::option::Option<i32>,
    /// Optional. Not supported with latest reasoning models `o3` and `o4-mini`. Up to 4 sequences where the API will
    /// stop generating further tokens. The returned text will not contain the stop sequence.
    #[prost(string, repeated, tag="25")]
    pub stop: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Optional. Whether to store the output of this chat completion request for use in model
    /// distillation, evals, or the stored completions dashboard.
    #[prost(bool, optional, tag="26")]
    pub store: ::core::option::Option<bool>,
    /// Optional. What sampling temperature to use, between 0 and 2. Higher values (e.g., 0.8) make the
    /// output more random, while lower values (e.g., 0.2) make it more focused and deterministic.
    #[prost(float, optional, tag="27")]
    pub temperature: ::core::option::Option<f32>,
    /// Optional. An integer between 0 and 20 specifying the number of most likely tokens to return at
    /// each token position, each with an associated log probability. Requires logprobs to be true.
    #[prost(int32, optional, tag="28")]
    pub top_logprobs: ::core::option::Option<i32>,
    /// Optional. An alternative to sampling with temperature, called nucleus sampling. The model
    /// considers only the tokens with top_p probability mass. Ranges from 0 to 1.
    #[prost(float, optional, tag="29")]
    pub top_p: ::core::option::Option<f32>,
    /// Optional. This field is being replaced by `safety_identifier` and `prompt_cache_key`. Use `prompt_cache_key`
    /// instead to maintain caching optimizations. A stable identifier for your end-users. Used to boost cache hit rates
    ///   by better bucketing similar requests and to help OpenAI detect and prevent abuse.
    /// [Learn more](<https://platform.openai.com/docs/guides/safety-best-practices#safety-identifiers>).
    #[prost(string, optional, tag="30")]
    pub user: ::core::option::Option<::prost::alloc::string::String>,
    /// Optional. Constrains the verbosity of the model's response. Lower values will result in more concise responses,
    /// while higher values will result in more verbose responses.
    /// Currently supported values are `low`, `medium`, and `high`.
    #[prost(enumeration="Verbosity", optional, tag="31")]
    pub verbosity: ::core::option::Option<i32>,
    /// Optional. Additional HTTP headers to send with the request. These are merged with and override
    /// default_headers for this specific request only.
    #[prost(message, optional, tag="32")]
    pub extra_headers: ::core::option::Option<::prost_types::Struct>,
    /// Optional. Additional query parameters to send with the request. These are merged with and override
    /// default_query for this specific request only.
    #[prost(message, optional, tag="33")]
    pub extra_query: ::core::option::Option<::prost_types::Struct>,
    /// Optional. Additional JSON properties to include in the request body. Useful for accessing new or
    /// undocumented API parameters.
    #[prost(message, optional, tag="34")]
    pub extra_body: ::core::option::Option<::prost_types::Struct>,
}
/// <p>VoiceActivityDetection contains information about voice activity detection settings.</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VoiceActivityDetection {
    /// Deprecated in favour of <code>vad_method</code>, but still honoured so that configurations
    /// written before that field existed keep working unchanged. One of &apos;pyannote&apos; or
    /// &apos;silero&apos;. Read only when <code>vad_method</code> is
    /// <code>VAD_METHOD_UNSPECIFIED</code>.
    #[prost(string, tag="1")]
    pub active: ::prost::alloc::string::String,
    /// Sampling rate for voice activity detection.
    #[prost(int64, tag="2")]
    pub sampling_rate: i64,
    /// Configuration for the Pyannote model. Read when Pyannote is the resolved VAD or TSD method.
    #[prost(message, optional, tag="3")]
    pub pyannote: ::core::option::Option<Pyannote>,
    /// Configuration for the Silero model. Read when Silero is the resolved VAD method.
    #[prost(message, optional, tag="4")]
    pub silero: ::core::option::Option<Silero>,
    /// Configuration for WeSpeaker target-speaker detection. Read when WeSpeaker is the resolved
    /// TSD method.
    #[prost(message, optional, tag="5")]
    pub wespeaker_tsd: ::core::option::Option<WespeakerTsd>,
    /// Which model splits the stream into utterances. Takes precedence over <code>active</code>;
    /// leave unset to keep using <code>active</code>.
    #[prost(enumeration="VadMethod", tag="6")]
    pub vad_method: i32,
    /// Which model decides whether an utterance came from the main speaker. Independent of
    /// <code>vad_method</code>, except that <code>TSD_METHOD_PYANNOTE</code> requires Pyannote to
    /// also be the active VAD. Leave unset to keep the behaviour of older configurations.
    #[prost(enumeration="TsdMethod", tag="7")]
    pub tsd_method: i32,
}
/// <p>Pyannote contains configuration for the Pyannote voice activity detection model.</p>
/// <p>Library: <a href="<https://github.com/pyannote/pyannote-audio/blob/develop/tutorials/voice_activity_detection.ipynb">pyannote-audio</a></p>>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Pyannote {
    /// Full name of the Pyannote model.
    #[prost(string, tag="1")]
    pub model_name: ::prost::alloc::string::String,
    /// Minimum audio size for processing.
    #[prost(int64, tag="2")]
    pub min_audio_size: i64,
    /// Fill inactive regions shorter than that many seconds.
    /// Example <a href="<https://github.com/pyannote/pyannote-audio/blob/develop/tutorials/voice_activity_detection.ipynb">notebook</a>>
    #[prost(float, tag="3")]
    pub min_duration_off: f32,
    /// Remove active regions shorter than that many seconds.
    /// Example <a href="<https://github.com/pyannote/pyannote-audio/blob/develop/tutorials/voice_activity_detection.ipynb">notebook</a>>
    #[prost(float, tag="4")]
    pub min_duration_on: f32,
    /// Host name of triton inference server that serves the Pyannote model
    #[prost(string, tag="5")]
    pub triton_server_host: ::prost::alloc::string::String,
    /// Port number of triton inference server that serves the Pyannote model
    #[prost(int64, tag="6")]
    pub triton_server_port: i64,
}
/// <p>Silero contains configuration for the Silero voice activity detection model.</p>
/// <p>Unlike <code>Pyannote</code>, Silero is configured with its own parameters rather than
/// <code>(min_duration_on, min_duration_off)</code>. They carry exactly the meaning they have
/// upstream in <code>get_speech_timestamps</code> / <code>VADIterator</code>.</p>
/// <p>Library: <a href="<https://github.com/snakers4/silero-vad">silero-vad</a></p>>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Silero {
    /// Full name of the Silero model.
    #[prost(string, tag="1")]
    pub model_name: ::prost::alloc::string::String,
    /// Minimum audio size for processing.
    #[prost(int64, tag="2")]
    pub min_audio_size: i64,
    /// Speech probability, in \[0, 1\], above which a frame counts as speech. A run of speech
    /// ends at the hysteresis threshold <code>threshold - 0.15</code>, as it does upstream, so
    /// this sets both the onset and - through that offset - the release point.
    /// Optional, and explicitly so: 0 is a legitimate value here, and without presence tracking
    /// it would be indistinguishable from an unset field and silently replaced by the default.
    #[prost(float, optional, tag="3")]
    pub threshold: ::core::option::Option<f32>,
    /// Speech runs shorter than this many milliseconds are discarded. A run still open at the
    /// end of the buffer is kept regardless, since more audio may extend it.
    /// Optional for the same reason as <code>threshold</code>: 0 means &apos;discard nothing&apos;.
    #[prost(float, optional, tag="4")]
    pub min_speech_duration_ms: ::core::option::Option<f32>,
    /// Silence, in milliseconds, that must follow the last speech before an utterance is
    /// declared to have ended.
    /// Optional for the same reason as <code>threshold</code>: 0 means &apos;end the utterance as
    /// soon as the speech stops&apos;.
    #[prost(float, optional, tag="5")]
    pub min_silence_duration_ms: ::core::option::Option<f32>,
    /// Padding, in milliseconds, added on each side of the detected boundary.
    /// Optional for the same reason as <code>threshold</code>: 0 means &apos;no padding&apos;.
    #[prost(float, optional, tag="6")]
    pub speech_pad_ms: ::core::option::Option<f32>,
    /// Host name of triton inference server that serves the Silero model
    #[prost(string, tag="7")]
    pub triton_server_host: ::prost::alloc::string::String,
    /// Port number of triton inference server that serves the Silero model
    #[prost(int64, tag="8")]
    pub triton_server_port: i64,
}
/// <p>WespeakerTsd contains configuration for the WeSpeaker target-speaker detection (TSD)
/// model. Given a reference speaker embedding, it decides whether a newly detected utterance
/// was spoken by the same person, so that speech from a different speaker (e.g. background
/// noise, crosstalk, or a barge-in) can be rejected.</p>
/// <p>Library: <a href="<https://huggingface.co/pyannote/wespeaker-voxceleb-resnet34-LM">wespeaker-voxceleb-resnet34-LM</a></p>>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WespeakerTsd {
    /// Indicates if target-speaker detection is active.
    #[prost(bool, tag="1")]
    pub active: bool,
    /// Full name of the WeSpeaker model.
    #[prost(string, tag="2")]
    pub model_name: ::prost::alloc::string::String,
    /// Host name of triton inference server that serves the WeSpeaker model
    #[prost(string, tag="3")]
    pub triton_server_host: ::prost::alloc::string::String,
    /// Port number of triton inference server that serves the WeSpeaker model
    #[prost(int64, tag="4")]
    pub triton_server_port: i64,
    /// Cosine similarity, in \[-1, 1\], above which a candidate utterance is judged to come
    /// from the same speaker as the reference.
    /// Optional, and explicitly so: 0 sits in the middle of the valid range, and without
    /// presence tracking it would be indistinguishable from an unset field.
    #[prost(float, optional, tag="5")]
    pub similarity_threshold: ::core::option::Option<f32>,
    /// Utterances shorter than this many seconds carry too little speaker information to
    /// judge, and are treated as undecided rather than rejected.
    /// Optional for the same reason as <code>similarity_threshold</code>: 0 means &apos;judge
    /// every utterance, however short&apos;.
    #[prost(float, optional, tag="6")]
    pub min_audio_length: ::core::option::Option<f32>,
    /// The reference audio is cropped to its most recent this-many seconds before being
    /// embedded.
    #[prost(float, tag="7")]
    pub reference_max_length: f32,
}
/// <p>PostProcessing contains the configuration for post-processing.</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PostProcessing {
    /// List of names of active post-processors.
    #[prost(string, repeated, tag="1")]
    pub pipeline: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Post-processor configurations.
    #[prost(message, optional, tag="2")]
    pub post_processors: ::core::option::Option<PostProcessors>,
}
/// <p>PostProcessors contains configurations for post-processors.</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PostProcessors {
    /// Configuration of the SymSpell spelling correction.
    #[prost(message, optional, tag="1")]
    pub sym_spell: ::core::option::Option<SymSpell>,
    /// Configuration of the normalization object.
    #[prost(message, optional, tag="2")]
    pub normalization: ::core::option::Option<S2tNormalization>,
    /// Configuration of the LLM post-processing.
    #[prost(message, optional, tag="3")]
    pub llm_post_processing: ::core::option::Option<S2tLlmPostProcessing>,
}
/// <p>SymSpell contains configuration for the SymSpell spelling correction.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SymSpell {
    /// Path to the dictionary used by symspell
    #[prost(string, tag="1")]
    pub dict_path: ::prost::alloc::string::String,
    /// The maximal edit-distance to consider for spelling correction (affects performance - bigger number
    /// takes longer to process!)
    #[prost(int64, tag="2")]
    pub max_dictionary_edit_distance: i64,
    /// The length (number of characters) of the prefix to consider for filtering
    #[prost(int64, tag="3")]
    pub prefix_length: i64,
}
/// <p>S2tNormalization contains configuration for the speech-to-text normalization.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct S2tNormalization {
    /// Language for normalization of transcriptions.
    #[prost(string, tag="1")]
    pub language: ::prost::alloc::string::String,
    /// List of names of active normalizations.
    #[prost(string, repeated, tag="2")]
    pub pipeline: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// <p>S2tLlmPostProcessing contains configuration for the speech-to-text postprocessing with LLM.</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct S2tLlmPostProcessing {
    /// Optional. Configuration options for the OpenAI client used for post-processing.
    #[prost(message, optional, tag="1")]
    pub s2t_llm_post_processing_openai_options: ::core::option::Option<OpenaiLlmOptions>,
    /// Optional. System prompt used to guide the LLM model for post-processing.
    #[prost(string, optional, tag="2")]
    pub s2t_llm_post_processing_system_prompt: ::core::option::Option<::prost::alloc::string::String>,
    /// Optional. Ending prompt appended to the accumulated prompts of the active post-processing tasks.
    #[prost(string, optional, tag="3")]
    pub s2t_llm_post_processing_ending_prompt: ::core::option::Option<::prost::alloc::string::String>,
    /// Optional. Configuration of the options to casing task in LLM post-processing.
    #[prost(message, optional, tag="4")]
    pub s2t_llm_post_processing_casing_options: ::core::option::Option<S2tLlmPostProcessingSubTaskOptions>,
    /// Optional. Configuration of the options to punctuation task in LLM post-processing.
    #[prost(message, optional, tag="5")]
    pub s2t_llm_post_processing_punctuation_options: ::core::option::Option<S2tLlmPostProcessingSubTaskOptions>,
    /// Optional. Configuration of the options to spelling-correction task in LLM post-processing.
    #[prost(message, optional, tag="6")]
    pub s2t_llm_post_processing_spelling_correction_options: ::core::option::Option<S2tLlmPostProcessingSubTaskOptions>,
    /// Optional. Configuration of the options to semantic-correction task in LLM post-processing.
    #[prost(message, optional, tag="7")]
    pub s2t_llm_post_processing_semantic_correction_options: ::core::option::Option<S2tLlmPostProcessingSubTaskOptions>,
    /// Optional. Configuration of the options to translation task in LLM post-processing.
    #[prost(message, optional, tag="8")]
    pub s2t_llm_post_processing_translation_options: ::core::option::Option<S2tLlmPostProcessingTranslationOptions>,
    /// Optional. Configuration of the options to inverse-normalization task in LLM post-processing.
    #[prost(message, optional, tag="9")]
    pub s2t_llm_post_processing_inverse_normalization_options: ::core::option::Option<S2tLlmPostProcessingInverseNormalizationOptions>,
    /// Optional. Configuration of the options to normalization task in LLM post-processing.
    #[prost(message, optional, tag="10")]
    pub s2t_llm_post_processing_normalization_options: ::core::option::Option<S2tLlmPostProcessingNormalizationOptions>,
    /// Optional. Configuration of the options to summarization task in LLM post-processing.
    #[prost(message, optional, tag="11")]
    pub s2t_llm_post_processing_summarization_options: ::core::option::Option<S2tLlmPostProcessingSummarizationOptions>,
    /// Optional. Configuration of the options to user-prompt task in LLM post-processing.
    #[prost(message, optional, tag="12")]
    pub s2t_llm_post_processing_user_prompt_options: ::core::option::Option<S2tLlmPostProcessingSubTaskOptions>,
}
/// <p>Configuration of the options to translation task in LLM post-processing.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct S2tLlmPostProcessingTranslationOptions {
    /// Optional. Indicates if the translation task of LLM post-processing is active.
    #[prost(bool, optional, tag="1")]
    pub active: ::core::option::Option<bool>,
    /// Optional. Target language of the translation task of LLM post-processing.
    #[prost(string, optional, tag="2")]
    pub language: ::core::option::Option<::prost::alloc::string::String>,
    /// Optional. Custom prompt to guide the LLM for translation. Overrides the default prompt when set.
    #[prost(string, optional, tag="3")]
    pub prompt: ::core::option::Option<::prost::alloc::string::String>,
}
/// <p>Configuration of the options to inverse-normalization task in LLM post-processing.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct S2tLlmPostProcessingInverseNormalizationOptions {
    /// Optional. Indicates if the inverse-normalization task of LLM post-processing is active.
    #[prost(bool, optional, tag="1")]
    pub active: ::core::option::Option<bool>,
    /// Optional. Configuration of the inverse-normalization of email address sub-task.
    #[prost(message, optional, tag="2")]
    pub email: ::core::option::Option<S2tLlmPostProcessingSubTaskOptions>,
    /// Optional. Configuration of the inverse-normalization of phone number sub-task.
    #[prost(message, optional, tag="3")]
    pub phone_number: ::core::option::Option<S2tLlmPostProcessingSubTaskOptions>,
    /// Optional. Configuration of the inverse-normalization of date and time sub-task.
    #[prost(message, optional, tag="4")]
    pub date_and_time: ::core::option::Option<S2tLlmPostProcessingSubTaskOptions>,
    /// Optional. Configuration of the inverse-normalization of credit card number sub-task.
    #[prost(message, optional, tag="5")]
    pub credit_card_number: ::core::option::Option<S2tLlmPostProcessingSubTaskOptions>,
    /// Optional. Configuration of the inverse-normalization of social security number sub-task.
    #[prost(message, optional, tag="6")]
    pub social_security_number: ::core::option::Option<S2tLlmPostProcessingSubTaskOptions>,
    /// Optional. Configuration of the inverse-normalization of time zone sub-task.
    #[prost(message, optional, tag="7")]
    pub time_zone: ::core::option::Option<S2tLlmPostProcessingSubTaskOptions>,
}
/// <p>Configuration of the options to normalization task in LLM post-processing.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct S2tLlmPostProcessingNormalizationOptions {
    /// Optional. Indicates if the normalization task of LLM post-processing is active.
    #[prost(bool, optional, tag="1")]
    pub active: ::core::option::Option<bool>,
    /// Optional. Configuration of the normalization of email address sub-task.
    #[prost(message, optional, tag="2")]
    pub email: ::core::option::Option<S2tLlmPostProcessingSubTaskOptions>,
    /// Optional. Configuration of the normalization of phone number sub-task.
    #[prost(message, optional, tag="3")]
    pub phone_number: ::core::option::Option<S2tLlmPostProcessingSubTaskOptions>,
    /// Optional. Configuration of the normalization of date and time sub-task.
    #[prost(message, optional, tag="4")]
    pub date_and_time: ::core::option::Option<S2tLlmPostProcessingSubTaskOptions>,
    /// Optional. Configuration of the normalization of credit card number sub-task.
    #[prost(message, optional, tag="5")]
    pub credit_card_number: ::core::option::Option<S2tLlmPostProcessingSubTaskOptions>,
    /// Optional. Configuration of the normalization of social security number sub-task.
    #[prost(message, optional, tag="6")]
    pub social_security_number: ::core::option::Option<S2tLlmPostProcessingSubTaskOptions>,
    /// Optional. Configuration of the normalization of time zone sub-task.
    #[prost(message, optional, tag="7")]
    pub time_zone: ::core::option::Option<S2tLlmPostProcessingSubTaskOptions>,
}
/// <p>Configuration of the options to summarization task in LLM post-processing.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct S2tLlmPostProcessingSummarizationOptions {
    /// Optional. Indicates if the summarization task of LLM post-processing is active.
    #[prost(bool, optional, tag="1")]
    pub active: ::core::option::Option<bool>,
    /// Optional. Custom prompt to guide the LLM for summarization. Overrides the default prompt when set.
    #[prost(string, optional, tag="2")]
    pub prompt: ::core::option::Option<::prost::alloc::string::String>,
    /// Optional. Minimum number of characters of the summary generated in summarization task of LLM post-processing.
    #[prost(int32, optional, tag="3")]
    pub min_chars: ::core::option::Option<i32>,
    /// Optional. Maximum number of characters of the summary generated in summarization task of LLM post-processing.
    #[prost(int32, optional, tag="4")]
    pub max_chars: ::core::option::Option<i32>,
}
/// <p>Common configuration for an individual LLM post-processing sub-task (e.g. email, phone number,
/// date and time, credit card number, social security number, time zone).
/// Used by both normalization and inverse-normalization tasks.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct S2tLlmPostProcessingSubTaskOptions {
    /// Optional. Indicates if this sub-task is active.
    #[prost(bool, optional, tag="1")]
    pub active: ::core::option::Option<bool>,
    /// Optional. Custom prompt to guide the LLM for this sub-task. Overrides the default prompt
    /// when set.
    #[prost(string, optional, tag="2")]
    pub prompt: ::core::option::Option<::prost::alloc::string::String>,
}
/// <p>Logging contains configuration for logging.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Logging {
    /// Type of logging.
    #[prost(string, tag="1")]
    pub r#type: ::prost::alloc::string::String,
    /// Path for logging.
    #[prost(string, tag="2")]
    pub path: ::prost::alloc::string::String,
}
// /////////////////////////////////////////
// GET LIST OF AVAILABLE LANGUAGE MODELS //
// /////////////////////////////////////////

/// <p>ListS2tLanguageModelsRequest is used to request a list of available language models for specified pipelines.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListS2tLanguageModelsRequest {
    /// List of pipeline IDs to retrieve their available language models.
    /// Example: \[&quot;pipeline_1&quot;, &quot;pipeline_2&quot;\]
    #[prost(string, repeated, tag="1")]
    pub ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// <p>LanguageModelPipelineId contains information about a pipeline and its available language models.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LanguageModelPipelineId {
    /// A pipeline ID. Example: &quot;pipeline_1&quot;
    #[prost(string, tag="1")]
    pub pipeline_id: ::prost::alloc::string::String,
    /// A list of all available language models for the corresponding pipeline ID. Example: \[&quot;model_1&quot;, &quot;model_2&quot;\]
    #[prost(string, repeated, tag="2")]
    pub model_names: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// <p>ListS2tLanguageModelsResponse is used to return the available language models for specified pipelines.</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListS2tLanguageModelsResponse {
    /// Response is a list of <code>LanguageModelPipelineId</code>, where each element contains a pipeline ID and its associated
    /// language models.
    /// Example: \[{pipeline_id: &quot;pipeline_1&quot;, model_names: [&quot;model_1&quot;, &quot;model_2&quot;\]}, {pipeline_id: &quot;pipeline_2&quot;,
    /// model_names: \[&quot;model_3&quot;\]}]
    #[prost(message, repeated, tag="1")]
    pub lm_pipeline_ids: ::prost::alloc::vec::Vec<LanguageModelPipelineId>,
}
// ///////////////////////////////////
// CUSTOM LANGUAGE MODEL FEATURES  //
// ///////////////////////////////////

/// <p>CreateUserLanguageModelRequest is used to request the creation of a new user-specific language model.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateUserLanguageModelRequest {
    /// Name of the language model to create. Example: &quot;user_lm_1&quot;
    #[prost(string, tag="1")]
    pub language_model_name: ::prost::alloc::string::String,
}
/// <p>DeleteUserLanguageModelRequest is used to request the deletion of a user-specific language model.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteUserLanguageModelRequest {
    /// Name of the language model to delete. Example: &quot;user_lm_1&quot;
    #[prost(string, tag="1")]
    pub language_model_name: ::prost::alloc::string::String,
}
/// <p>AddDataToUserLanguageModelRequest is used to request the addition of data to a user-specific language model.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AddDataToUserLanguageModelRequest {
    /// Name of the language model to which to add data. Example: &quot;user_lm_1&quot;
    #[prost(string, tag="1")]
    pub language_model_name: ::prost::alloc::string::String,
    /// Zip file containing data in the form of text files.
    /// Example: A zip file with text files containing sentences or phrases in the target language.
    #[prost(bytes="vec", tag="2")]
    pub zipped_data: ::prost::alloc::vec::Vec<u8>,
}
/// <p>TrainUserLanguageModelRequest is used to request the training of a user-specific language model.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TrainUserLanguageModelRequest {
    /// Name of the language model to train. Example: &quot;user_lm_1&quot;
    #[prost(string, tag="1")]
    pub language_model_name: ::prost::alloc::string::String,
    /// Order n of the ngram. Example: 3 (for trigram model)
    #[prost(int64, tag="2")]
    pub order: i64,
}
// //////////////////////
// LIST OF S2T NORMALIZATION PIPELINES //
// //////////////////////

/// <p>The request message for <code>ListS2tNormalizationPipelines</code>.</p>
/// <p>Filter pipelines by attributes in request.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListS2tNormalizationPipelinesRequest {
    /// Optional. Define the language.
    #[prost(string, tag="1")]
    pub language: ::prost::alloc::string::String,
}
/// <p>The response message for <code>ListS2tNormalizationPipelines</code>.</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListS2tNormalizationPipelinesResponse {
    /// Required. Representation of a list of normalization pipelines configurations.
    /// Retrieved by <code>ListS2tNormalizationPipelines</code>, containing the configurations of
    /// normalization pipelines with the specifications received in the <code>ListS2tNormalizationPipelinesRequest</code>.
    #[prost(string, repeated, tag="1")]
    pub s2t_normalization_pipelines: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
// /////////////////////////
//          Enums         //
// /////////////////////////

/// The decoding configuration
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Decoding {
    /// decoding will be defined by the pipeline config
    Default = 0,
    /// greedy decoding will be used independently on pipeline config
    Greedy = 1,
    /// beam search will be used independently on pipeline config
    BeamSearchWithLm = 2,
    /// beam search without LM head, to configure decoding mode for seq2seq models.
    BeamSearch = 3,
}
impl Decoding {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Default => "DEFAULT",
            Self::Greedy => "GREEDY",
            Self::BeamSearchWithLm => "BEAM_SEARCH_WITH_LM",
            Self::BeamSearch => "BEAM_SEARCH",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DEFAULT" => Some(Self::Default),
            "GREEDY" => Some(Self::Greedy),
            "BEAM_SEARCH_WITH_LM" => Some(Self::BeamSearchWithLm),
            "BEAM_SEARCH" => Some(Self::BeamSearch),
            _ => None,
        }
    }
}
/// The inference backend configuration
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum InferenceBackend {
    /// Not set
    Unknown = 0,
    /// Run pytorch model
    Pytorch = 1,
    /// Run flax model
    Flax = 2,
    /// Run Amazon S2T cloud service
    CloudServiceAmazon = 3,
    /// Run Deepgram S2T cloud service
    CloudServiceDeepgram = 4,
    /// Run Google S2T cloud service
    CloudServiceGoogle = 5,
    /// Run Microsoft Azure S2T cloud service
    CloudServiceMicrosoft = 6,
}
impl InferenceBackend {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "INFERENCE_BACKEND_UNKNOWN",
            Self::Pytorch => "INFERENCE_BACKEND_PYTORCH",
            Self::Flax => "INFERENCE_BACKEND_FLAX",
            Self::CloudServiceAmazon => "INFERENCE_BACKEND_CLOUD_SERVICE_AMAZON",
            Self::CloudServiceDeepgram => "INFERENCE_BACKEND_CLOUD_SERVICE_DEEPGRAM",
            Self::CloudServiceGoogle => "INFERENCE_BACKEND_CLOUD_SERVICE_GOOGLE",
            Self::CloudServiceMicrosoft => "INFERENCE_BACKEND_CLOUD_SERVICE_MICROSOFT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "INFERENCE_BACKEND_UNKNOWN" => Some(Self::Unknown),
            "INFERENCE_BACKEND_PYTORCH" => Some(Self::Pytorch),
            "INFERENCE_BACKEND_FLAX" => Some(Self::Flax),
            "INFERENCE_BACKEND_CLOUD_SERVICE_AMAZON" => Some(Self::CloudServiceAmazon),
            "INFERENCE_BACKEND_CLOUD_SERVICE_DEEPGRAM" => Some(Self::CloudServiceDeepgram),
            "INFERENCE_BACKEND_CLOUD_SERVICE_GOOGLE" => Some(Self::CloudServiceGoogle),
            "INFERENCE_BACKEND_CLOUD_SERVICE_MICROSOFT" => Some(Self::CloudServiceMicrosoft),
            _ => None,
        }
    }
}
/// <p>Latency tier to use for processing an OpenAI request. Affects cost and throughput.</p>
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ServiceTier {
    /// Unspecified service tier.
    Unspecified = 0,
    /// Auto service tier.
    Auto = 1,
    /// Default service tier.
    Default = 2,
    /// Flex service tier.
    Flex = 3,
    /// Scale service tier.
    Scale = 4,
    /// Priority service tier.
    Priority = 5,
}
impl ServiceTier {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "SERVICE_TIER_UNSPECIFIED",
            Self::Auto => "SERVICE_TIER_AUTO",
            Self::Default => "SERVICE_TIER_DEFAULT",
            Self::Flex => "SERVICE_TIER_FLEX",
            Self::Scale => "SERVICE_TIER_SCALE",
            Self::Priority => "SERVICE_TIER_PRIORITY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SERVICE_TIER_UNSPECIFIED" => Some(Self::Unspecified),
            "SERVICE_TIER_AUTO" => Some(Self::Auto),
            "SERVICE_TIER_DEFAULT" => Some(Self::Default),
            "SERVICE_TIER_FLEX" => Some(Self::Flex),
            "SERVICE_TIER_SCALE" => Some(Self::Scale),
            "SERVICE_TIER_PRIORITY" => Some(Self::Priority),
            _ => None,
        }
    }
}
/// <p>Verbosity level for the response output.</p>
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Verbosity {
    /// Unspecified verbosity.
    Unspecified = 0,
    /// Low verbosity.
    Low = 1,
    /// Medium verbosity.
    Medium = 2,
    /// High verbosity.
    High = 3,
}
impl Verbosity {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "VERBOSITY_UNSPECIFIED",
            Self::Low => "VERBOSITY_LOW",
            Self::Medium => "VERBOSITY_MEDIUM",
            Self::High => "VERBOSITY_HIGH",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "VERBOSITY_UNSPECIFIED" => Some(Self::Unspecified),
            "VERBOSITY_LOW" => Some(Self::Low),
            "VERBOSITY_MEDIUM" => Some(Self::Medium),
            "VERBOSITY_HIGH" => Some(Self::High),
            _ => None,
        }
    }
}
/// <p>Effort level for reasoning models (e.g., o1, o3). Controls the trade-off between speed and quality.</p>
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ReasoningEffort {
    /// Unspecified reasoning effort.
    Unspecified = 0,
    /// Minimal reasoning effort.
    Minimal = 1,
    /// Low reasoning effort.
    Low = 2,
    /// Medium reasoning effort.
    Medium = 3,
    /// High reasoning effort.
    High = 4,
}
impl ReasoningEffort {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "REASONING_EFFORT_UNSPECIFIED",
            Self::Minimal => "REASONING_EFFORT_MINIMAL",
            Self::Low => "REASONING_EFFORT_LOW",
            Self::Medium => "REASONING_EFFORT_MEDIUM",
            Self::High => "REASONING_EFFORT_HIGH",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "REASONING_EFFORT_UNSPECIFIED" => Some(Self::Unspecified),
            "REASONING_EFFORT_MINIMAL" => Some(Self::Minimal),
            "REASONING_EFFORT_LOW" => Some(Self::Low),
            "REASONING_EFFORT_MEDIUM" => Some(Self::Medium),
            "REASONING_EFFORT_HIGH" => Some(Self::High),
            _ => None,
        }
    }
}
/// <p>VadMethod selects the model used to split the audio stream into utterances.</p>
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum VadMethod {
    /// No explicit choice. The method is then taken from the legacy
    /// <code>VoiceActivityDetection.active</code> string, and from Pyannote if that is empty too.
    Unspecified = 0,
    /// Use the Pyannote segmentation model, configured by <code>VoiceActivityDetection.pyannote</code>.
    Pyannote = 1,
    /// Use the Silero model, configured by <code>VoiceActivityDetection.silero</code>.
    Silero = 2,
}
impl VadMethod {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "VAD_METHOD_UNSPECIFIED",
            Self::Pyannote => "VAD_METHOD_PYANNOTE",
            Self::Silero => "VAD_METHOD_SILERO",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "VAD_METHOD_UNSPECIFIED" => Some(Self::Unspecified),
            "VAD_METHOD_PYANNOTE" => Some(Self::Pyannote),
            "VAD_METHOD_SILERO" => Some(Self::Silero),
            _ => None,
        }
    }
}
/// <p>TsdMethod selects the model used for target-speaker detection (TSD): deciding whether a
/// newly detected utterance came from the main speaker of the call, so that speech from anyone
/// else (crosstalk, background speakers, barge-in) can be rejected.</p>
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TsdMethod {
    /// No explicit choice. TSD then follows the behaviour of older configurations that predate
    /// this field, which is keyed on the active VAD: Pyannote whenever Pyannote is the VAD, since
    /// its segmentation model doubles as a speaker filter; otherwise WeSpeaker if
    /// <code>wespeaker_tsd.active</code> is set; otherwise no TSD at all. Note that
    /// <code>wespeaker_tsd.active</code> is deliberately not consulted on the Pyannote path,
    /// because it was never consulted there before this field existed.
    Unspecified = 0,
    /// Disable target-speaker detection. Every detected utterance is transcribed, whoever spoke it.
    None = 1,
    /// Reuse the Pyannote segmentation model, which distinguishes speakers in addition to
    /// detecting speech. Available only when Pyannote is also the active VAD.
    Pyannote = 2,
    /// Use the dedicated WeSpeaker embedding model, configured by
    /// <code>VoiceActivityDetection.wespeaker_tsd</code>. Works with any VAD.
    Wespeaker = 3,
}
impl TsdMethod {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "TSD_METHOD_UNSPECIFIED",
            Self::None => "TSD_METHOD_NONE",
            Self::Pyannote => "TSD_METHOD_PYANNOTE",
            Self::Wespeaker => "TSD_METHOD_WESPEAKER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TSD_METHOD_UNSPECIFIED" => Some(Self::Unspecified),
            "TSD_METHOD_NONE" => Some(Self::None),
            "TSD_METHOD_PYANNOTE" => Some(Self::Pyannote),
            "TSD_METHOD_WESPEAKER" => Some(Self::Wespeaker),
            _ => None,
        }
    }
}
include!("ondewo.s2t.tonic.rs");
// @@protoc_insertion_point(module)
