// @generated
// This file is @generated by prost-build.
/// <p>Ends an ongoing call of the active SIP session of the active SIP account</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SipEndCallRequest {
    /// Set to <code>True</code> to forcefully hang up the call
    #[prost(bool, tag="1")]
    pub hard_hangup: bool,
    /// Optional: reason for ending the call. Leave unset for an ordinary hangup
    #[prost(enumeration="sip_end_call_request::EndCallReason", tag="2")]
    pub end_reason: i32,
    /// Optional: result of the answering machine detection that decided to end the call. Only meaningful together with
    /// <code>end_reason = ANSWERING_MACHINE</code> or <code>end_reason = ANSWERING_MACHINE_VOICE_MESSAGE_LEFT</code>;
    /// it is carried into <code>SipStatus.amd_result</code> of the terminal status of the call
    #[prost(message, optional, tag="3")]
    pub amd_result: ::core::option::Option<AnsweringMachineDetectionResult>,
}
/// Nested message and enum types in `SipEndCallRequest`.
pub mod sip_end_call_request {
    /// <p>Why the call is being ended</p>
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum EndCallReason {
        /// No specific reason given. The call ends as an ordinary hangup, exactly as before this field existed
        Unspecified = 0,
        /// Answering machine detection decided the callee is not a person to talk to (answering machine, fax,
        /// network announcement, ...) and the call is hung up WITHOUT leaving a voice message. The terminal status
        /// of the call is <code>OUTGOING_CALL_FINISHED</code> with the description
        /// <code>Answering machine detected with hang up</code>
        AnsweringMachine = 1,
        /// Answering machine detection decided the callee is an answering machine, a voice message was left on it,
        /// and the call is hung up afterwards (or when the voice message timeout expired). The terminal status of
        /// the call is <code>OUTGOING_CALL_FINISHED</code> with the description
        /// <code>Answering machine detected with left voice message and hang up</code>
        AnsweringMachineVoiceMessageLeft = 2,
        /// A WARM transfer completed: the transfer target joined the call and the bot leaves it. The terminal status of
        /// the call is <code>*_CALL_FINISHED</code> with the description <code>Call transferred</code> and
        /// <code>transfer_call_id</code> set to the transfer target
        Transferred = 3,
    }
    impl EndCallReason {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Unspecified => "END_CALL_REASON_UNSPECIFIED",
                Self::AnsweringMachine => "ANSWERING_MACHINE",
                Self::AnsweringMachineVoiceMessageLeft => "ANSWERING_MACHINE_VOICE_MESSAGE_LEFT",
                Self::Transferred => "END_CALL_REASON_TRANSFERRED",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "END_CALL_REASON_UNSPECIFIED" => Some(Self::Unspecified),
                "ANSWERING_MACHINE" => Some(Self::AnsweringMachine),
                "ANSWERING_MACHINE_VOICE_MESSAGE_LEFT" => Some(Self::AnsweringMachineVoiceMessageLeft),
                "END_CALL_REASON_TRANSFERRED" => Some(Self::Transferred),
                _ => None,
            }
        }
    }
}
/// <p>Reports the verdict of the answering machine detection of the ongoing outgoing call</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SipReportAnsweringMachineDetectedRequest {
    /// Result of the answering machine detection. Written to <code>SipStatus.amd_result</code> of the
    /// <code>OUTGOING_CALL_ANSWERING_MACHINE_DETECTED</code> status of the call
    #[prost(message, optional, tag="1")]
    pub amd_result: ::core::option::Option<AnsweringMachineDetectionResult>,
}
/// <p>Result of the answering machine detection (AMD) of an outbound call</p>
/// <p>Carries identifiers from closed vocabularies only: never audio, transcript text or a phone number</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AnsweringMachineDetectionResult {
    /// Who or what answered the call
    #[prost(enumeration="answering_machine_detection_result::Verdict", tag="1")]
    pub verdict: i32,
    /// Evidence that led to the verdict
    #[prost(enumeration="answering_machine_detection_result::Cause", tag="2")]
    pub cause: i32,
    /// Confidence of the verdict, between <code>0.0</code> and <code>1.0</code>
    #[prost(float, tag="3")]
    pub confidence: f32,
    /// Time in milliseconds from the call being connected until the verdict was reached
    #[prost(int32, tag="4")]
    pub decision_ms: i32,
    /// Identifier of the detection rule that produced the verdict
    #[prost(string, tag="5")]
    pub rule_id: ::prost::alloc::string::String,
    /// Identifiers of the cues that matched, e.g. keyword or tone identifiers. Identifiers only, never transcript text
    #[prost(string, repeated, tag="6")]
    pub matched_cue_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// What was done because of the verdict
    #[prost(enumeration="answering_machine_detection_result::ActionTaken", tag="7")]
    pub action_taken: i32,
    /// Identifier of the call the result belongs to, i.e. the value of the <code>X-ondewo-vtsi-caller-call-id</code>
    /// header of the call. Used to match a result to its call by identity rather than by recency
    #[prost(string, tag="8")]
    pub call_id: ::prost::alloc::string::String,
}
/// Nested message and enum types in `AnsweringMachineDetectionResult`.
pub mod answering_machine_detection_result {
    /// <p>Who or what answered the call</p>
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum Verdict {
        /// No verdict available
        Unspecified = 0,
        /// A person answered the call
        Human = 1,
        /// An answering machine or voicemail answered the call
        Machine = 2,
        /// An interactive voice response system (IVR) answered the call
        Ivr = 3,
        /// A fax machine answered the call
        Fax = 4,
        /// A network announcement answered the call, e.g. "the number you have dialed is not available"
        NetworkAnnouncement = 5,
        /// A call screening service answered the call, e.g. asking the caller to state their name
        CallScreening = 6,
        /// Nothing was said within the detection window
        NoSpeech = 7,
        /// The detection could not decide
        Unknown = 8,
    }
    impl Verdict {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Unspecified => "VERDICT_UNSPECIFIED",
                Self::Human => "HUMAN",
                Self::Machine => "MACHINE",
                Self::Ivr => "IVR",
                Self::Fax => "FAX",
                Self::NetworkAnnouncement => "NETWORK_ANNOUNCEMENT",
                Self::CallScreening => "CALL_SCREENING",
                Self::NoSpeech => "NO_SPEECH",
                Self::Unknown => "UNKNOWN",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "VERDICT_UNSPECIFIED" => Some(Self::Unspecified),
                "HUMAN" => Some(Self::Human),
                "MACHINE" => Some(Self::Machine),
                "IVR" => Some(Self::Ivr),
                "FAX" => Some(Self::Fax),
                "NETWORK_ANNOUNCEMENT" => Some(Self::NetworkAnnouncement),
                "CALL_SCREENING" => Some(Self::CallScreening),
                "NO_SPEECH" => Some(Self::NoSpeech),
                "UNKNOWN" => Some(Self::Unknown),
                _ => None,
            }
        }
    }
    /// <p>Evidence that led to the verdict</p>
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum Cause {
        /// No cause available
        Unspecified = 0,
        /// The speech cadence, e.g. a long uninterrupted greeting
        Cadence = 1,
        /// A keyword or phrase typical of the verdict
        Keyword = 2,
        /// A voicemail beep
        Beep = 3,
        /// A tone, e.g. a fax or special information tone
        Tone = 4,
        /// Both the speech cadence and a keyword
        CadenceAndKeyword = 5,
        /// Both the speech cadence and a voicemail beep
        CadenceAndBeep = 6,
        /// The detection window ended before any other evidence decided
        Timeout = 7,
        /// Silence throughout the detection window
        Silence = 8,
    }
    impl Cause {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Unspecified => "CAUSE_UNSPECIFIED",
                Self::Cadence => "CADENCE",
                Self::Keyword => "KEYWORD",
                Self::Beep => "BEEP",
                Self::Tone => "TONE",
                Self::CadenceAndKeyword => "CADENCE_AND_KEYWORD",
                Self::CadenceAndBeep => "CADENCE_AND_BEEP",
                Self::Timeout => "TIMEOUT",
                Self::Silence => "SILENCE",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "CAUSE_UNSPECIFIED" => Some(Self::Unspecified),
                "CADENCE" => Some(Self::Cadence),
                "KEYWORD" => Some(Self::Keyword),
                "BEEP" => Some(Self::Beep),
                "TONE" => Some(Self::Tone),
                "CADENCE_AND_KEYWORD" => Some(Self::CadenceAndKeyword),
                "CADENCE_AND_BEEP" => Some(Self::CadenceAndBeep),
                "TIMEOUT" => Some(Self::Timeout),
                "SILENCE" => Some(Self::Silence),
                _ => None,
            }
        }
    }
    /// <p>What was done because of the verdict</p>
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum ActionTaken {
        /// No action recorded
        Unspecified = 0,
        /// The call was hung up
        HungUp = 1,
        /// The call continued as normal
        Continued = 2,
        /// Detection only: the verdict was recorded, but the call was not influenced by it
        DetectOnly = 3,
        /// A voice message was left on the answering machine, and the call was hung up afterwards
        LeftVoiceMessage = 4,
    }
    impl ActionTaken {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Unspecified => "ACTION_TAKEN_UNSPECIFIED",
                Self::HungUp => "HUNG_UP",
                Self::Continued => "CONTINUED",
                Self::DetectOnly => "DETECT_ONLY",
                Self::LeftVoiceMessage => "LEFT_VOICE_MESSAGE",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "ACTION_TAKEN_UNSPECIFIED" => Some(Self::Unspecified),
                "HUNG_UP" => Some(Self::HungUp),
                "CONTINUED" => Some(Self::Continued),
                "DETECT_ONLY" => Some(Self::DetectOnly),
                "LEFT_VOICE_MESSAGE" => Some(Self::LeftVoiceMessage),
                _ => None,
            }
        }
    }
}
/// <p>Request to start the call with the active SIP session of the active SIP account</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SipStartCallRequest {
    /// SIP account name
    #[prost(string, tag="1")]
    pub callee_id: ::prost::alloc::string::String,
    /// Headers to include when starting the call
    #[prost(map="string, string", tag="2")]
    pub headers: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
/// <p>Request for registering a SIP account at a SIP server</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SipRegisterAccountRequest {
    /// Account name of the sip user. Usually something like <code>sip-user-1@mydomain.com</code> or <code>sip-user-1@192.168.123.123</code> which uses the default SIP port <code>5060</code>.
    /// Also a non-default SIP port can be specified via <code>sip-user-1@mydomain.com:5099</code> to connect to a SIP server running on port <code>5099</code>
    #[prost(string, tag="1")]
    pub account_name: ::prost::alloc::string::String,
    /// Password of the account
    #[prost(string, tag="2")]
    pub password: ::prost::alloc::string::String,
    /// Optional: authentication user name
    #[prost(string, tag="3")]
    pub auth_username: ::prost::alloc::string::String,
    /// Optional: outbound proxy address, e.g. <code>my.outbound.proxy.com</code>
    #[prost(string, tag="4")]
    pub outbound_proxy: ::prost::alloc::string::String,
}
/// <p>Request for starting a new SIP session for a specified account</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SipStartSessionRequest {
    /// Account name of the sip user. Usually something like <code>sip-user-1@mydomain.com</code> or <code>sip-user-1@192.168.123.123</code> which uses the default SIP port <code>5060</code>.
    /// Also a non-default SIP port can be specified via <code>sip-user-1@mydomain.com:5099</code> to connect to a SIP server running on port <code>5099</code>
    #[prost(string, tag="1")]
    pub account_name: ::prost::alloc::string::String,
    /// Auto-answer interval in seconds. The call will be automatically answered after this interval
    #[prost(int32, tag="2")]
    pub auto_answer_interval: i32,
}
/// <p>Request for transferring a call with or without headers</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SipTransferCallRequest {
    /// The account name or phone number to transfer the call to
    #[prost(string, tag="1")]
    pub transfer_id: ::prost::alloc::string::String,
    /// The headers to include when transferring the call. They are sent on the REFER. Note that Asterisk (res_pjsip,
    /// measured on 18.6 and 22) does NOT forward headers of a REFER to the transfer target: the target receives the
    /// headers of the transferred caller's original INVITE. Hand headers to the target through the dialplan instead
    #[prost(map="string, string", tag="2")]
    pub headers: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    /// <p>Optional. How long to wait, in milliseconds, for the SIP server's answer to the REFER before reporting the outcome.
    /// Clamped to 10000.</p>
    /// <p><code>0</code> (default): legacy behaviour, unchanged: REFER, then an immediate hangup.</p>
    /// <p><code>&gt; 0</code>: the call is kept until the outcome is known:</p>
    /// <ul>
    ///    <li>REFER accepted (<code>202</code>): the hangup is held for a short grace in which a terminal NOTIFY with a
    ///    <code>404</code> sipfrag (unknown target) still counts as a refusal; any other sipfrag, or none, means accepted.
    ///    The bot then hangs up and <code>TRANSFER_CALL_INITIATED</code> is returned with
    ///    <code>sip_response_code = 202</code>. The call ends as <code>*_CALL_FINISHED</code> with the description
    ///    <code>Call transferred</code>.</li>
    ///    <li>REFER refused (a final response <code>&gt;= 400</code>, or the <code>404</code> sipfrag above): the call is KEPT
    ///    with the bot, nothing is assigned to the shared status, and <code>TRANSFER_CALL_FAILED</code> is returned with
    ///    <code>description = reason=refer-rejected</code> and <code>sip_response_code</code> (<code>0</code> when the SIP
    ///    stack did not report the code, e.g. a declined REFER).</li>
    ///    <li>No answer within the timeout: the call is KEPT and <code>TRANSFER_CALL_FAILED</code> is returned with
    ///    <code>description = reason=refer-timeout</code>. A late acceptance still ends the bot's leg.</li>
    ///    <li>The call ended while waiting: <code>NO_ONGOING_CALL</code> is returned.</li>
    /// </ul>
    /// <p>A <code>202</code> does not mean the target answered: when the dialplan's dial to the target then fails (busy, no
    /// answer, unreachable) the caller is lost. Validate targets up front, or use a WARM transfer.</p>
    #[prost(uint32, tag="3")]
    pub outcome_timeout_ms: u32,
}
/// <p>Status information for a SIP account, session, or call</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SipStatus {
    /// Account name of the sip user. Usually something like <code>sip-user-1@mydomain.com</code> or <code>sip-user-1@192.168.123.123</code> which uses the default SIP port <code>5060</code>.
    /// Also a non-default SIP port can be specified via <code>sip-user-1@mydomain.com:5099</code> to connect to a SIP server running on port <code>5099</code>
    #[prost(string, tag="1")]
    pub account_name: ::prost::alloc::string::String,
    /// Timestamp of the status
    #[prost(message, optional, tag="2")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    /// Status type
    #[prost(enumeration="sip_status::StatusType", tag="3")]
    pub status_type: i32,
    /// SIP account name
    #[prost(string, tag="4")]
    pub callee_id: ::prost::alloc::string::String,
    /// SIP account of the transfer
    #[prost(string, tag="5")]
    pub transfer_call_id: ::prost::alloc::string::String,
    /// Headers to include when calling outbound or transfer
    #[prost(map="string, string", tag="6")]
    pub headers: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    /// More detailed description of the status
    #[prost(string, tag="7")]
    pub description: ::prost::alloc::string::String,
    /// Name of the exception
    #[prost(string, tag="8")]
    pub exception_name: ::prost::alloc::string::String,
    /// Traceback of the exception
    #[prost(string, tag="9")]
    pub exception_traceback: ::prost::alloc::string::String,
    /// session name of the NLU session
    #[prost(string, tag="10")]
    pub nlu_session_name: ::prost::alloc::string::String,
    /// Result of the answering machine detection of the call. Set on
    /// <code>OUTGOING_CALL_ANSWERING_MACHINE_DETECTED</code> and on the terminal status of every call on which answering machine detection ran, including a
    /// <code>HUMAN</code> verdict; unset otherwise
    #[prost(message, optional, tag="11")]
    pub amd_result: ::core::option::Option<AnsweringMachineDetectionResult>,
    /// Identifier of the ongoing call, minted per call: the value of the <code>X-ondewo-vtsi-caller-call-id</code> header of
    /// an outgoing call when present, otherwise a random UUID. Empty when no call is ongoing. Set on every status of the
    /// call, including the entries of <code>SipGetSipStatusHistory</code>. Clients send it back as the
    /// <code>x-ondewo-expected-call-id</code> metadatum to scope a request to this call
    #[prost(string, tag="12")]
    pub call_id: ::prost::alloc::string::String,
    /// <code>true</code> while the bot is muted by an operator, a conference participant policy or a TALK take-over of
    /// <code>SipSetCallMediaControl</code> / <code>SipStreamCallAudio</code>. Not the bot's own pipeline mute
    /// (<code>MICROPHONE_MUTED</code>). Cleared when the call ends
    #[prost(bool, tag="13")]
    pub bot_muted: bool,
    /// <code>true</code> while the bot does not listen to the caller (see <code>bot_muted</code> for who sets it). Cleared
    /// when the call ends
    #[prost(bool, tag="14")]
    pub listening_paused: bool,
    /// Number of connected <code>SipStreamCallAudio</code> streams of the ongoing call
    #[prost(int32, tag="15")]
    pub call_audio_streams: i32,
    /// SIP response code of the last transfer attempt of the ongoing call (<code>202</code> when accepted, the refusal code
    /// otherwise, <code>0</code> when unknown). Call-scoped
    #[prost(int32, tag="16")]
    pub sip_response_code: i32,
}
/// Nested message and enum types in `SipStatus`.
pub mod sip_status {
    /// Types of status
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum StatusType {
        /// No session is currently active
        NoSession = 0,
        /// SIP account is registered at a SIP server
        Registered = 1,
        /// SIP account is ready to call
        Ready = 2,
        /// SIP account is being called, i.e. inbound/incoming call
        IncomingCallInitiated = 3,
        /// SIP account starts calling, i.e. outbound/outgoing call
        OutgoingCallInitiated = 4,
        /// SIP account outbound call is connected
        OutgoingCallConnected = 5,
        /// SIP account incoming call is connected
        IncomingCallConnected = 6,
        /// SIP account starts transferring the call
        TransferCallInitiated = 7,
        /// SIP account hangs up the ongoing call
        SoftHangupInitiated = 8,
        /// SIP account forcefully hangs up by terminating the SIP program
        HardHangupInitiated = 9,
        /// SIP account cannot accept the incoming call
        IncomingCallFailed = 10,
        /// SIP account cannot do an outbound call
        OutgoingCallFailed = 11,
        /// SIP account finished the ongoing incoming call
        IncomingCallFinished = 12,
        /// SIP account finished the ongoing outgoing call
        OutgoingCallFinished = 13,
        /// Registration of SIP account to SIP server failed
        SessionRegistrationFailed = 14,
        /// SIP account started a new SIP session via a SIP server
        SessionStarted = 15,
        /// SIP account ended active sip session with SIP server
        SessionEnded = 16,
        /// SIP account cannot transfer the call
        TransferCallFailed = 17,
        /// Microphone is muted
        MicrophoneMuted = 18,
        /// Microphone is unmuted
        MicrophoneUnmuted = 19,
        /// Microphone has played wav files
        MicrophoneWavFilesPlayed = 20,
        /// No ongoing call
        NoOngoingCall = 21,
        /// Answering machine detection decided the callee of the ongoing outgoing call is not a person to talk to.
        /// NOT terminal: the call is still up when this status is set. <code>amd_result.verdict</code> tells an
        /// answering machine, a fax, a network announcement, ... apart. The call then ends as
        /// <code>OUTGOING_CALL_FINISHED</code> carrying <code>amd_result</code> and exactly one of the descriptions
        /// <code>Answering machine detected with hang up</code>,
        /// <code>Answering machine detected with left voice message and hang up</code>,
        /// <code>Answering machine detected, call ended by the answering machine</code> or
        /// <code>Answering machine detected, call ended by the answering machine after leaving a voice message</code>
        OutgoingCallAnsweringMachineDetected = 22,
    }
    impl StatusType {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::NoSession => "NO_SESSION",
                Self::Registered => "REGISTERED",
                Self::Ready => "READY",
                Self::IncomingCallInitiated => "INCOMING_CALL_INITIATED",
                Self::OutgoingCallInitiated => "OUTGOING_CALL_INITIATED",
                Self::OutgoingCallConnected => "OUTGOING_CALL_CONNECTED",
                Self::IncomingCallConnected => "INCOMING_CALL_CONNECTED",
                Self::TransferCallInitiated => "TRANSFER_CALL_INITIATED",
                Self::SoftHangupInitiated => "SOFT_HANGUP_INITIATED",
                Self::HardHangupInitiated => "HARD_HANGUP_INITIATED",
                Self::IncomingCallFailed => "INCOMING_CALL_FAILED",
                Self::OutgoingCallFailed => "OUTGOING_CALL_FAILED",
                Self::IncomingCallFinished => "INCOMING_CALL_FINISHED",
                Self::OutgoingCallFinished => "OUTGOING_CALL_FINISHED",
                Self::SessionRegistrationFailed => "SESSION_REGISTRATION_FAILED",
                Self::SessionStarted => "SESSION_STARTED",
                Self::SessionEnded => "SESSION_ENDED",
                Self::TransferCallFailed => "TRANSFER_CALL_FAILED",
                Self::MicrophoneMuted => "MICROPHONE_MUTED",
                Self::MicrophoneUnmuted => "MICROPHONE_UNMUTED",
                Self::MicrophoneWavFilesPlayed => "MICROPHONE_WAV_FILES_PLAYED",
                Self::NoOngoingCall => "NO_ONGOING_CALL",
                Self::OutgoingCallAnsweringMachineDetected => "OUTGOING_CALL_ANSWERING_MACHINE_DETECTED",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "NO_SESSION" => Some(Self::NoSession),
                "REGISTERED" => Some(Self::Registered),
                "READY" => Some(Self::Ready),
                "INCOMING_CALL_INITIATED" => Some(Self::IncomingCallInitiated),
                "OUTGOING_CALL_INITIATED" => Some(Self::OutgoingCallInitiated),
                "OUTGOING_CALL_CONNECTED" => Some(Self::OutgoingCallConnected),
                "INCOMING_CALL_CONNECTED" => Some(Self::IncomingCallConnected),
                "TRANSFER_CALL_INITIATED" => Some(Self::TransferCallInitiated),
                "SOFT_HANGUP_INITIATED" => Some(Self::SoftHangupInitiated),
                "HARD_HANGUP_INITIATED" => Some(Self::HardHangupInitiated),
                "INCOMING_CALL_FAILED" => Some(Self::IncomingCallFailed),
                "OUTGOING_CALL_FAILED" => Some(Self::OutgoingCallFailed),
                "INCOMING_CALL_FINISHED" => Some(Self::IncomingCallFinished),
                "OUTGOING_CALL_FINISHED" => Some(Self::OutgoingCallFinished),
                "SESSION_REGISTRATION_FAILED" => Some(Self::SessionRegistrationFailed),
                "SESSION_STARTED" => Some(Self::SessionStarted),
                "SESSION_ENDED" => Some(Self::SessionEnded),
                "TRANSFER_CALL_FAILED" => Some(Self::TransferCallFailed),
                "MICROPHONE_MUTED" => Some(Self::MicrophoneMuted),
                "MICROPHONE_UNMUTED" => Some(Self::MicrophoneUnmuted),
                "MICROPHONE_WAV_FILES_PLAYED" => Some(Self::MicrophoneWavFilesPlayed),
                "NO_ONGOING_CALL" => Some(Self::NoOngoingCall),
                "OUTGOING_CALL_ANSWERING_MACHINE_DETECTED" => Some(Self::OutgoingCallAnsweringMachineDetected),
                _ => None,
            }
        }
    }
}
/// <p>History of SIP status</p>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SipStatusHistoryResponse {
    /// History of SIP status
    #[prost(message, repeated, tag="1")]
    pub status_history: ::prost::alloc::vec::Vec<SipStatus>,
}
/// <p>Request of <code>SipSetCallMediaControl</code></p>
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SipSetCallMediaControlRequest {
    /// <code>MEDIA_CONTROL_SETTING_ON</code>: the bot speaks. <code>MEDIA_CONTROL_SETTING_OFF</code>: the bot is muted
    #[prost(enumeration="MediaControlSetting", tag="1")]
    pub bot_voice: i32,
    /// <code>MEDIA_CONTROL_SETTING_ON</code>: caller audio reaches speech-to-text. <code>MEDIA_CONTROL_SETTING_OFF</code>:
    /// listening is paused
    #[prost(enumeration="MediaControlSetting", tag="2")]
    pub bot_listening: i32,
    /// Owner whose hold is set
    #[prost(enumeration="MediaControlOwner", tag="3")]
    pub owner: i32,
    /// <p>Only for <code>MEDIA_CONTROL_OWNER_PARTICIPANT</code>, ignored for every other owner: whether at least one
    /// invited participant is ringing or joined. Every participant request carries the full value, so the request that
    /// reports the last participant gone sends <code>false</code>.</p>
    /// <p>While participants are present (this flag, or a mute or pause held by the participant owner)
    /// <code>SipTransferCall</code> is refused with <code>exception_name=ParticipantsPresent</code>, because a REFER
    /// into a conference bridge transfers every party in it. A request that would mark participants present while a
    /// transfer of the call is in flight is refused with <code>exception_name=TransferInProgress</code> and changes
    /// nothing. Cleared when the call ends</p>
    #[prost(bool, tag="4")]
    pub participants_present: bool,
}
/// <p>Configuration of a <code>SipStreamCallAudio</code> stream. Must be the first request of the stream</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SipCallAudioConfig {
    /// Mode of the stream. Unspecified means LISTEN
    #[prost(enumeration="SipCallAudioMode", tag="1")]
    pub mode: i32,
    /// Sample rate in Hz of the audio in both directions: <code>8000</code> or <code>16000</code>. <code>0</code> means
    /// <code>16000</code>
    #[prost(int32, tag="2")]
    pub sample_rate_hz: i32,
    /// Frame length in milliseconds. Only <code>20</code> is supported; <code>0</code> means <code>20</code>
    #[prost(int32, tag="3")]
    pub frame_ms: i32,
    /// REQUIRED for TALK: the bot is muted and does not listen while the stream is connected. Released when the stream
    /// ends
    #[prost(bool, tag="4")]
    pub take_over: bool,
    /// Identifier of the stream for logs and audit correlation, minted by the client (a UUID)
    #[prost(string, tag="5")]
    pub stream_id: ::prost::alloc::string::String,
    /// Maximum duration of the stream in seconds. <code>0</code> means the server default (3600)
    #[prost(int32, tag="6")]
    pub max_duration_s: i32,
}
/// <p>One frame of call audio</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SipCallAudioFrame {
    /// LINEAR16 little-endian mono samples of one frame, i.e. <code>sample_rate_hz * frame_ms / 1000 * 2</code> bytes
    #[prost(bytes="vec", tag="1")]
    pub pcm_s16le: ::prost::alloc::vec::Vec<u8>,
    /// Monotonic sequence number of the frame within its direction of the stream
    #[prost(uint64, tag="2")]
    pub sequence: u64,
}
/// <p>Request of <code>SipStreamCallAudio</code></p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SipCallAudioRequest {
    /// One of the following
    #[prost(oneof="sip_call_audio_request::Request", tags="1, 2, 3")]
    pub request: ::core::option::Option<sip_call_audio_request::Request>,
}
/// Nested message and enum types in `SipCallAudioRequest`.
pub mod sip_call_audio_request {
    /// One of the following
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Request {
        /// Configuration; must be the first request and is accepted only once
        #[prost(message, tag="1")]
        Config(super::SipCallAudioConfig),
        /// Agent audio to send to the caller (TALK only)
        #[prost(message, tag="2")]
        Audio(super::SipCallAudioFrame),
        /// <code>true</code>: the agent's audio is not sent to the caller (silence instead) until set to <code>false</code>
        #[prost(bool, tag="3")]
        AgentMuted(bool),
    }
}
/// <p>Sent once when a <code>SipStreamCallAudio</code> stream is connected</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SipCallAudioStarted {
    /// Identifier of the stream
    #[prost(string, tag="1")]
    pub stream_id: ::prost::alloc::string::String,
    /// Sample rate in Hz of the audio in both directions
    #[prost(int32, tag="2")]
    pub sample_rate_hz: i32,
    /// Frame length in milliseconds
    #[prost(int32, tag="3")]
    pub frame_ms: i32,
    /// Mode of the stream
    #[prost(enumeration="SipCallAudioMode", tag="4")]
    pub mode: i32,
}
/// <p>Counters of a <code>SipStreamCallAudio</code> stream, sent periodically</p>
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SipCallAudioStats {
    /// Frames sent to the client
    #[prost(uint64, tag="1")]
    pub frames_sent: u64,
    /// Frames to the client dropped because the client read too slowly
    #[prost(uint64, tag="2")]
    pub frames_dropped: u64,
    /// Frames received from the client
    #[prost(uint64, tag="3")]
    pub frames_received: u64,
    /// Playback underruns of the agent audio (silence was played)
    #[prost(uint64, tag="4")]
    pub underruns: u64,
    /// Frames from the client discarded because the playback buffer was full
    #[prost(uint64, tag="5")]
    pub frames_discarded: u64,
}
/// <p>Sent once when a <code>SipStreamCallAudio</code> stream ends normally</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SipCallAudioEnded {
    /// Why the stream ended
    #[prost(enumeration="SipCallAudioEndReason", tag="1")]
    pub reason: i32,
    /// Optional detail, a stable token
    #[prost(string, tag="2")]
    pub detail: ::prost::alloc::string::String,
}
/// <p>Response of <code>SipStreamCallAudio</code></p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SipCallAudioResponse {
    /// One of the following
    #[prost(oneof="sip_call_audio_response::Response", tags="1, 2, 3, 4")]
    pub response: ::core::option::Option<sip_call_audio_response::Response>,
}
/// Nested message and enum types in `SipCallAudioResponse`.
pub mod sip_call_audio_response {
    /// One of the following
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Response {
        /// The stream is connected
        #[prost(message, tag="1")]
        Started(super::SipCallAudioStarted),
        /// Call audio
        #[prost(message, tag="2")]
        Audio(super::SipCallAudioFrame),
        /// Stream counters
        #[prost(message, tag="3")]
        Stats(super::SipCallAudioStats),
        /// The stream ended
        #[prost(message, tag="4")]
        Ended(super::SipCallAudioEnded),
    }
}
/// <p>Plays a list of wav files</p>
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SipPlayWavFilesRequest {
    /// Wav files as bytes in a list that will be played
    #[prost(bytes="vec", repeated, tag="1")]
    pub wav_files: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
/// <p>Desired setting of one media control flag</p>
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MediaControlSetting {
    /// Leave the flag as it is for this owner
    Unchanged = 0,
    /// The flag is on: the bot speaks (<code>bot_voice</code>) or the bot listens (<code>bot_listening</code>)
    On = 1,
    /// The flag is off: the bot is muted (<code>bot_voice</code>) or the bot's listening is paused (<code>bot_listening</code>)
    Off = 2,
}
impl MediaControlSetting {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unchanged => "MEDIA_CONTROL_SETTING_UNCHANGED",
            Self::On => "MEDIA_CONTROL_SETTING_ON",
            Self::Off => "MEDIA_CONTROL_SETTING_OFF",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MEDIA_CONTROL_SETTING_UNCHANGED" => Some(Self::Unchanged),
            "MEDIA_CONTROL_SETTING_ON" => Some(Self::On),
            "MEDIA_CONTROL_SETTING_OFF" => Some(Self::Off),
            _ => None,
        }
    }
}
/// <p>Owner of a media control hold. Each owner holds its own mute and pause; releasing one owner's hold never releases
/// another owner's</p>
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MediaControlOwner {
    /// Same as <code>MEDIA_CONTROL_OWNER_OPERATOR</code>
    Unspecified = 0,
    /// An operator, e.g. a supervisor muting the bot
    Operator = 1,
    /// The bot policy of invited conference participants, set while at least one participant is ringing or joined. Its
    /// hold mutes or pauses the bot only when a participant's bot policy asks for it; it also carries
    /// <code>SipSetCallMediaControlRequest.participants_present</code>
    Participant = 2,
}
impl MediaControlOwner {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "MEDIA_CONTROL_OWNER_UNSPECIFIED",
            Self::Operator => "MEDIA_CONTROL_OWNER_OPERATOR",
            Self::Participant => "MEDIA_CONTROL_OWNER_PARTICIPANT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MEDIA_CONTROL_OWNER_UNSPECIFIED" => Some(Self::Unspecified),
            "MEDIA_CONTROL_OWNER_OPERATOR" => Some(Self::Operator),
            "MEDIA_CONTROL_OWNER_PARTICIPANT" => Some(Self::Participant),
            _ => None,
        }
    }
}
/// <p>Mode of a <code>SipStreamCallAudio</code> stream</p>
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SipCallAudioMode {
    /// Same as <code>SIP_CALL_AUDIO_MODE_LISTEN</code>
    Unspecified = 0,
    /// Receive the call audio only
    Listen = 1,
    /// Receive the caller's audio and send audio to the caller. Requires <code>take_over</code>
    Talk = 2,
}
impl SipCallAudioMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "SIP_CALL_AUDIO_MODE_UNSPECIFIED",
            Self::Listen => "SIP_CALL_AUDIO_MODE_LISTEN",
            Self::Talk => "SIP_CALL_AUDIO_MODE_TALK",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SIP_CALL_AUDIO_MODE_UNSPECIFIED" => Some(Self::Unspecified),
            "SIP_CALL_AUDIO_MODE_LISTEN" => Some(Self::Listen),
            "SIP_CALL_AUDIO_MODE_TALK" => Some(Self::Talk),
            _ => None,
        }
    }
}
/// <p>Why a <code>SipStreamCallAudio</code> stream ended</p>
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SipCallAudioEndReason {
    /// No reason recorded
    Unspecified = 0,
    /// The client cancelled or half-closed the stream
    ClientClosed = 1,
    /// The call ended
    CallEnded = 2,
    /// The call was transferred
    CallTransferred = 3,
    /// <code>max_duration_s</code> was reached
    MaxDuration = 4,
    /// The client did not read the audio in time
    Stalled = 5,
    /// An internal error ended the stream
    Internal = 6,
}
impl SipCallAudioEndReason {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "SIP_CALL_AUDIO_END_REASON_UNSPECIFIED",
            Self::ClientClosed => "SIP_CALL_AUDIO_END_REASON_CLIENT_CLOSED",
            Self::CallEnded => "SIP_CALL_AUDIO_END_REASON_CALL_ENDED",
            Self::CallTransferred => "SIP_CALL_AUDIO_END_REASON_CALL_TRANSFERRED",
            Self::MaxDuration => "SIP_CALL_AUDIO_END_REASON_MAX_DURATION",
            Self::Stalled => "SIP_CALL_AUDIO_END_REASON_STALLED",
            Self::Internal => "SIP_CALL_AUDIO_END_REASON_INTERNAL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SIP_CALL_AUDIO_END_REASON_UNSPECIFIED" => Some(Self::Unspecified),
            "SIP_CALL_AUDIO_END_REASON_CLIENT_CLOSED" => Some(Self::ClientClosed),
            "SIP_CALL_AUDIO_END_REASON_CALL_ENDED" => Some(Self::CallEnded),
            "SIP_CALL_AUDIO_END_REASON_CALL_TRANSFERRED" => Some(Self::CallTransferred),
            "SIP_CALL_AUDIO_END_REASON_MAX_DURATION" => Some(Self::MaxDuration),
            "SIP_CALL_AUDIO_END_REASON_STALLED" => Some(Self::Stalled),
            "SIP_CALL_AUDIO_END_REASON_INTERNAL" => Some(Self::Internal),
            _ => None,
        }
    }
}
include!("ondewo.sip.tonic.rs");
// @@protoc_insertion_point(module)
